const products = [
  {
    id: 1,
    name: "Kemeja Oxford Slim Fit Putih Pria",
    category: "kemeja",
    gender: "Pria",
    price: 329000,
    stock: 21,
    description: "Kemeja Oxford slim fit warna putih berbahan katun yang nyaman dengan kerah klasik dan kancing depan. Cocok untuk bekerja, kuliah, maupun acara semi-formal.",
    color: "Putih",
    size: ["S", "M", "L", "XL"],
    image: "https://cdn.shopify.com/s/files/1/0207/9406/files/02_Cotton_Oxford_White_Model_Front_8daf81a4-6d02-4ecd-815e-f82c0f89c37c.jpg?v=1745932223&width=600"
  },
  {
    id: 2,
    name: "Hoodie Oversize Fleece Cream Wanita",
    category: "hoodie",
    gender: "Wanita",
    price: 289000,
    stock: 24,
    description: "Hoodie oversize warna cream berbahan fleece lembut dengan potongan longgar. Nyaman digunakan untuk aktivitas santai dan gaya kasual sehari-hari.",
    color: "Cream",
    size: ["S", "M", "L", "XL"],
    image: "https://cdn.platform.next/common/items/default/default/itemimages/3_4Ratio/product/lge/K49808s.jpg"
  },
  {
    id: 3,
    name: "Sepatu Sneakers Casual Putih Pria",
    category: "sepatu",
    gender: "Pria",
    price: 429000,
    stock: 18,
    description: "Sneakers casual warna putih dengan desain minimalis, sol fleksibel, dan bantalan nyaman untuk berjalan maupun aktivitas harian.",
    color: "Putih",
    size: ["39", "40", "41", "42", "43"],
    image: "https://hips.hearstapps.com/hmg-prod/images/index-68cc54bc00b60.jpg?crop=0.498xw:1xh;center,top&resize=640:*"
  },
  {
    id: 4,
    name: "Piyama Satin Lilac Wanita",
    category: "piyama",
    gender: "Wanita",
    price: 239000,
    stock: 19,
    description: "Set piyama satin warna lilac dengan tekstur halus dan ringan. Terdiri dari atasan berkancing dan celana panjang yang nyaman untuk tidur dan bersantai.",
    color: "Lilac",
    size: ["S", "M", "L", "XL"],
    image: "https://i5.walmartimages.com/asr/abf8eb93-8dbd-4fc9-b834-44080a6e4775.6b685a081a9bffb63c9f5266ea21f91a.jpeg?odnHeight=1067&odnWidth=800&odnBg=FFFFFF"
  },
  {
    id: 5,
    name: "Tas Crossbody Canvas Navy Pria",
    category: "tas",
    gender: "Pria",
    price: 219000,
    stock: 27,
    description: "Tas crossbody berbahan canvas warna navy dengan tali bahu yang dapat disesuaikan. Memiliki ruang praktis untuk dompet, ponsel, dan barang kecil.",
    color: "Navy",
    size: ["All Size"],
    image: "https://myspringfield.com/on/demandware.static/-/Sites-gc-spf-master-catalog/default/dwd8ffeaff/images/hi-res/P_096385297D1.jpg"
  },
  {
    id: 6,
    name: "Sweater Knit Cable Olive Pria",
    category: "sweater",
    gender: "Pria",
    price: 329000,
    stock: 20,
    description: "Sweater rajut cable knit warna olive dengan tekstur rajutan klasik dan bahan hangat. Cocok dipakai untuk tampilan kasual saat cuaca sejuk.",
    color: "Olive",
    size: ["M", "L", "XL", "XXL"],
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRSwx8fWEnygPq89BKFj2FmyPVnRdLvLM7vQm63CzHFMg&s=10"
  },
  {
    id: 7,
    name: "Kaos Oversize Basic Putih Wanita",
    category: "kaos",
    gender: "Wanita",
    price: 129000,
    stock: 35,
    description: "Kaos oversize basic warna putih berbahan cotton yang lembut dan nyaman. Potongannya longgar sehingga mudah dipadukan dengan jeans, rok, atau celana santai.",
    color: "Putih",
    size: ["S", "M", "L", "XL"],
    image: "https://www.nuuds.com/cdn/shop/files/Gen1_W-1015-WHIT-S_On-Model_Front-Crop_savanna-1.jpg?v=1764116764&width=1920"
  },
  {
    id: 8,
    name: "Kebaya Brokat Modern Dusty Pink",
    category: "kebaya",
    gender: "Wanita",
    price: 675000,
    stock: 12,
    description: "Kebaya modern berbahan brokat warna dusty pink dengan detail motif floral yang elegan. Cocok untuk acara keluarga, wisuda, lamaran, dan perayaan formal.",
    color: "Dusty Pink",
    size: ["S", "M", "L", "XL"],
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQKIeNOfNZL9-AVoFyTtkp_lS8474EiJmcqOufX9wJfxSakcz_FlD3CoqI&s=10"
  },
  {
    id: 9,
    name: "Kemeja Linen Relaxed Fit Beige Wanita",
    category: "kemeja",
    gender: "Wanita",
    price: 289000,
    stock: 17,
    description: "Kemeja linen relaxed fit warna beige dengan bahan ringan dan sirkulasi udara yang baik. Cocok untuk gaya kasual, liburan, maupun aktivitas sehari-hari.",
    color: "Beige",
    size: ["S", "M", "L", "XL"],
    image: "https://d29c1z66frfv6c.cloudfront.net/pub/media/catalog/product/zoom/2e305242420e1937ffaed04a8256f4140d973ac4_xxl-1.jpg"
  },
  {
    id: 10,
    name: "Sepatu Running Mesh Abu-abu Wanita",
    category: "sepatu",
    gender: "Wanita",
    price: 389000,
    stock: 23,
    description: "Sepatu running berbahan mesh warna abu-abu dengan desain ringan dan breathable. Cocok digunakan untuk olahraga ringan, jogging, maupun aktivitas harian.",
    color: "Abu-abu",
    size: ["36", "37", "38", "39", "40"],
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQDdJyP-kH0W1bfwDpK84EoUe6sNviDHJZsGz06tEN-cg&s=10"
  },
  {
    id: 11,
    name: "Hoodie Zip Basic Hitam Pria",
    category: "hoodie",
    gender: "Pria",
    price: 299000,
    stock: 28,
    description: "Hoodie zip warna hitam dengan desain minimalis, hoodie bertali, dan bukaan resleting depan. Cocok untuk gaya santai dan streetwear.",
    color: "Hitam",
    size: ["M", "L", "XL", "XXL"],
    image: "https://dynamic.zacdn.com/46tNe90X8sFhmfHB0Q2q0aXLG7c=/filters:quality(70):format(webp)/https://static-id.zacdn.com/p/gloaming-5075-2213214-1.jpg"
  },
  {
    id: 12,
    name: "Kaos Graphic Navy Pria",
    category: "kaos",
    gender: "Pria",
    price: 149000,
    stock: 41,
    description: "Kaos graphic warna navy berbahan cotton dengan potongan relaxed fit. Detail grafis memberikan kesan modern dan cocok untuk gaya kasual sehari-hari.",
    color: "Navy",
    size: ["M", "L", "XL", "XXL"],
    image: "https://cultstore.com/cdn/shop/files/705418_A_b4380498-1470-471c-9824-0d5ebf5b55f9.jpg?v=1755675476&width=963"
  },
  {
    id: 13,
    name: "Kebaya Kutubaru Brokat Sage",
    category: "kebaya",
    gender: "Wanita",
    price: 745000,
    stock: 9,
    description: "Kebaya kutubaru berbahan brokat warna sage dengan detail klasik dan tampilan anggun. Cocok untuk acara tradisional, keluarga, dan perayaan formal.",
    color: "Sage",
    size: ["S", "M", "L", "XL"],
    image: "https://p16-oec-va.ibyteimg.com/tos-maliva-i-o3syd03w52-us/b7a0512d31804f2ea626318bb3614229~tplv-o3syd03w52-resize-jpeg:500:500.jpeg"
  },
  {
    id: 14,
    name: "Sweater Crewneck Cream Wanita",
    category: "sweater",
    gender: "Wanita",
    price: 249000,
    stock: 26,
    description: "Sweater crewneck warna cream dengan bahan lembut dan potongan regular fit. Mudah dipadukan dengan celana jeans atau rok untuk gaya kasual.",
    color: "Cream",
    size: ["S", "M", "L", "XL"],
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRQtCgJjEEeV24z4BGsqsHxWaOTo8lFhApbQvJXjb-eIA&s=10"
  },
  {
    id: 15,
    name: "Piyama Katun Motif Biru Pria",
    category: "piyama",
    gender: "Pria",
    price: 189000,
    stock: 22,
    description: "Set piyama katun warna biru dengan motif sederhana dan bahan ringan. Nyaman digunakan untuk tidur dan bersantai di rumah.",
    color: "Biru",
    size: ["M", "L", "XL", "XXL"],
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRc8Z6J2hi-CE8xtgypo4nWUqeh4xiiH2QDYqdmD_HZrg&s"
  },
  {
    id: 16,
    name: "Tas Tote Kanvas Beige Wanita",
    category: "tas",
    gender: "Wanita",
    price: 179000,
    stock: 32,
    description: "Tas tote berbahan kanvas warna beige dengan ukuran cukup luas untuk membawa barang kebutuhan harian. Desain sederhana cocok untuk kuliah, kerja, atau belanja.",
    color: "Beige",
    size: ["All Size"],
    image: "https://levi.co.id/cdn/shop/files/005FV0003_1_CM_DA_e9926a89-156e-440e-8f1e-1078b104baad.jpg?v=1766740282&width=1920"
  },
  {
    id: 17,
    name: "Kemeja Flannel Kotak Merah Pria",
    category: "kemeja",
    gender: "Pria",
    price: 239000,
    stock: 29,
    description: "Kemeja flannel motif kotak warna merah dengan bahan lembut dan nyaman. Bisa digunakan sebagai kemeja utama maupun outer untuk gaya kasual.",
    color: "Merah",
    size: ["M", "L", "XL", "XXL"],
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRXAvGXm_xjpjZey94nY5DQsE6b1pUVZNJqrBCKuZVlhvB3z88CX09zJSJr&s=10"
  },
  {
    id: 18,
    name: "Tas Shoulder Quilted Hitam Wanita",
    category: "tas",
    gender: "Wanita",
    price: 329000,
    stock: 20,
    description: "Tas shoulder quilted warna hitam dengan desain elegan dan tali bahu yang nyaman. Ukurannya praktis untuk membawa ponsel, dompet, dan perlengkapan kecil.",
    color: "Hitam",
    size: ["All Size"],
    image: "https://www.skechers.id/cdn/shop/files/0888-SKESBD5024BK-3.jpg?v=1774425824&width=1445"
  },
  {
    id: 19,
    name: "Hoodie Pullover Graphic Abu-abu Pria",
    category: "hoodie",
    gender: "Pria",
    price: 319000,
    stock: 25,
    description: "Hoodie pullover warna abu-abu dengan detail graphic pada bagian depan. Berbahan fleece lembut dengan potongan santai untuk gaya streetwear.",
    color: "Abu-abu",
    size: ["M", "L", "XL", "XXL"],
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQRu-OccJF2wFcudwbTMMIGzWcQqvRr2EOCbmYzipQIrg&s=10"
  },
  {
    id: 20,
    name: "Kaos Ribbed Slim Fit Hitam Wanita",
    category: "kaos",
    gender: "Wanita",
    price: 139000,
    stock: 31,
    description: "Kaos ribbed slim fit warna hitam dengan tekstur bergaris halus dan bahan elastis. Cocok dipadukan dengan jeans, rok, maupun outer.",
    color: "Hitam",
    size: ["S", "M", "L", "XL"],
    image: "https://cdn.4f.com.pl/media/catalog/product/4/F/4FWSS25TTSHF1968-20S-M-03-MAIN.jpg?im=Resize=(930,920)"
  },
  {
    id: 21,
    name: "Piyama Rayon Sage Wanita",
    category: "piyama",
    gender: "Wanita",
    price: 199000,
    stock: 27,
    description: "Set piyama rayon warna sage dengan bahan jatuh, ringan, dan lembut di kulit. Desain santai cocok untuk tidur maupun bersantai di rumah.",
    color: "Sage",
    size: ["S", "M", "L", "XL"],
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSYuXhEO2r6iGVbOsy3b-orJsdkUP_3ZwUy7-wlNxo_jV5yAK7N8LS1UlqP&s=10"
  },
  {
    id: 22,
    name: "Sepatu Loafers Kulit Cokelat Pria",
    category: "sepatu",
    gender: "Pria",
    price: 579000,
    stock: 14,
    description: "Loafers kulit warna cokelat dengan desain klasik dan tampilan rapi. Cocok digunakan bersama celana bahan, chino, maupun outfit semi-formal.",
    color: "Cokelat",
    size: ["39", "40", "41", "42", "43"],
    image: "https://cdn.shopify.com/s/files/1/0419/1525/files/1024x1024-Mens-Lincoln-RichMahogany-092623-3.4.jpg?v=1696879812"
  },
  {
    id: 23,
    name: "Sweater Half Zip Navy Pria",
    category: "sweater",
    gender: "Pria",
    price: 339000,
    stock: 15,
    description: "Sweater half zip warna navy dengan kerah tinggi dan resleting pendek pada bagian depan. Cocok untuk gaya kasual dan aktivitas luar ruangan.",
    color: "Navy",
    size: ["M", "L", "XL", "XXL"],
    image: "https://whitmanstore.com/cdn/shop/files/SacoHPrescoltHalfZipAzulNavy1.jpg?v=1775660679"
  },
  {
    id: 24,
    name: "Kebaya Encim Modern Ivory",
    category: "kebaya",
    gender: "Wanita",
    price: 715000,
    stock: 11,
    description: "Kebaya encim modern warna ivory dengan detail bordir yang lembut dan feminin. Cocok untuk acara budaya, keluarga, pernikahan, dan perayaan resmi.",
    color: "Ivory",
    size: ["S", "M", "L", "XL"],
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSOvvLDx_ZpbkDQBV2YGNQJCyDnwpU8zphY3u5E5XFbz7fVLVcGRuynO8Yg&s=10"
  },
  {
    id: 25,
    name: "Kaos Polo Cotton Navy Pria",
    category: "kaos",
    gender: "Pria",
    price: 179000,
    stock: 37,
    description: "Kaos polo berbahan cotton warna navy dengan kerah dan kancing depan. Memberikan tampilan kasual yang lebih rapi untuk berbagai aktivitas.",
    color: "Navy",
    size: ["M", "L", "XL", "XXL"],
    image: "https://xcdn.next.co.uk/common/items/default/default/itemimages/3_4Ratio/product/lge/B58602s5.jpg?im=Resize,width=750"
  },
  {
    id: 26,
    name: "Hoodie Crop Fleece Dusty Pink Wanita",
    category: "hoodie",
    gender: "Wanita",
    price: 279000,
    stock: 22,
    description: "Hoodie crop berbahan fleece warna dusty pink dengan potongan pendek yang modern. Cocok untuk dipadukan dengan high waist jeans atau rok.",
    color: "Dusty Pink",
    size: ["S", "M", "L", "XL"],
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSnGwwVbIz-NwYKMdg9bpzZy1D9QSdBROiT-aMp535EG5T5KvJji51z248&s=10"
  },
  {
    id: 27,
    name: "Kemeja Poplin Puff Sleeve Putih Wanita",
    category: "kemeja",
    gender: "Wanita",
    price: 259000,
    stock: 20,
    description: "Kemeja poplin warna putih dengan detail puff sleeve dan kerah klasik. Memberikan tampilan feminin dan rapi untuk acara santai maupun semi-formal.",
    color: "Putih",
    size: ["S", "M", "L", "XL"],
    image: "https://shopaleena.com/cdn/shop/files/poplin-puff-sleeve-shirt-with-fabric-buttonsshopaleena-990248.jpg?v=1750127158&width=2048"
  },
  {
    id: 28,
    name: "Sepatu Mary Jane Flat Hitam Wanita",
    category: "sepatu",
    gender: "Wanita",
    price: 299000,
    stock: 18,
    description: "Sepatu Mary Jane flat warna hitam dengan strap pada bagian atas dan desain feminin. Nyaman dipadukan dengan rok, dress, maupun celana.",
    color: "Hitam",
    size: ["36", "37", "38", "39", "40"],
    image: "https://m.media-amazon.com/images/I/71nRGQyO7-L._AC_UY900_.jpg"
  },
  {
    id: 29,
    name: "Sweater Waffle Cream Pria",
    category: "sweater",
    gender: "Pria",
    price: 289000,
    stock: 22,
    description: "Sweater berbahan cotton waffle warna cream dengan tekstur kotak khas. Potongannya santai dan cocok digunakan untuk gaya kasual sehari-hari.",
    color: "Cream",
    size: ["M", "L", "XL", "XXL"],
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTK9VqE3Cj20TC3js07IWSwSch0JEe0KrP_oFUi2YCI_38_kWjKSALHpZoZ&s=10"
  },
  {
    id: 30,
    name: "Tas Sling Bag Canvas Olive Pria",
    category: "tas",
    gender: "Pria",
    price: 169000,
    stock: 33,
    description: "Sling bag canvas warna olive dengan ukuran compact dan tali bahu yang dapat disesuaikan. Cocok untuk membawa ponsel, dompet, kunci, dan barang kecil.",
    color: "Olive",
    size: ["All Size"],
    image: "https://images.jdmagicbox.com/quickquotes/images_main/storite-canvas-sling-cross-body-messenger-college-one-side-shoulder-bag-for-men-w-kurta-omen-olive-26-x-8-x-21-cm-272191889-tubqy.jpg"
  },

  {
    id: 31,
    name: "Piyama Satin Navy Wanita",
    category: "piyama",
    gender: "Wanita",
    price: 259000,
    stock: 14,
    description: "Set piyama satin warna navy dengan atasan berkancing dan celana panjang. Materialnya halus dengan tampilan elegan untuk tidur dan bersantai.",
    color: "Navy",
    size: ["S", "M", "L", "XL"],
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRBOibGVV-I_7amuKBAHL5DyrXbPZDfXjSrotn_qeqmQg&s=10"
  },
  {
    id: 32,
    name: "Kemeja Linen Short Sleeve Sand Pria",
    category: "kemeja",
    gender: "Pria",
    price: 269000,
    stock: 22,
    description: "Kemeja linen lengan pendek warna sand dengan bahan ringan dan breathable. Cocok untuk liburan, aktivitas santai, dan gaya kasual sehari-hari.",
    color: "Sand",
    size: ["M", "L", "XL", "XXL"],
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTxKg-6FwEnmGIsqfcVjT1a1HuAUnq23-2OBKyTVQjOnQ&s"
  },
  {
    id: 33,
    name: "Sepatu Slip On Knit Beige Wanita",
    category: "sepatu",
    gender: "Wanita",
    price: 329000,
    stock: 25,
    description: "Sepatu slip on berbahan knit warna beige dengan desain praktis tanpa tali. Ringan dan fleksibel untuk digunakan saat bepergian maupun aktivitas harian.",
    color: "Beige",
    size: ["36", "37", "38", "39", "40"],
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRxIgur9sJCVSkfykLz38D9m7YL2vlEQ9KMW4oYWxRMpA&s"
  },
  {
    id: 34,
    name: "Kaos Henley Cotton Olive Pria",
    category: "kaos",
    gender: "Pria",
    price: 159000,
    stock: 29,
    description: "Kaos henley cotton warna olive dengan tiga kancing pada bagian leher. Memiliki potongan regular dan nyaman untuk gaya kasual pria.",
    color: "Olive",
    size: ["M", "L", "XL", "XXL"],
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTP4v0QN4fHEiAi9Zo1qMiyh_XC-hALgBNAqrbrN-9Jng&s"
  },
  {
    id: 35,
    name: "Kebaya Brokat Payet Champagne",
    category: "kebaya",
    gender: "Wanita",
    price: 895000,
    stock: 7,
    description: "Kebaya brokat warna champagne dengan detail payet yang memberikan kesan mewah dan elegan. Cocok untuk pesta, lamaran, pernikahan, dan acara formal.",
    color: "Champagne",
    size: ["S", "M", "L", "XL"],
    image: "https://i.pinimg.com/736x/fa/55/3f/fa553fa148136cd0fe49ee0cb2750933.jpg"
  },
  {
    id: 36,
    name: "Hoodie French Terry Navy Pria",
    category: "hoodie",
    gender: "Pria",
    price: 309000,
    stock: 23,
    description: "Hoodie berbahan French terry warna navy dengan tekstur nyaman dan daya serap yang baik. Cocok untuk aktivitas santai dan gaya kasual pria.",
    color: "Navy",
    size: ["M", "L", "XL", "XXL"],
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSwrXaLBYdFct-ZjKZ1FtDKWgJ2TPav6JEP5yI-kK0AWfnK2l_eOKRXuck&s=10"
  },
  {
    id: 37,
    name: "Sweater Knit Striped Navy Wanita",
    category: "sweater",
    gender: "Wanita",
    price: 299000,
    stock: 20,
    description: "Sweater knit motif garis warna navy dengan bahan rajut lembut. Cocok digunakan bersama celana panjang, jeans, atau rok untuk gaya kasual.",
    color: "Navy",
    size: ["S", "M", "L", "XL"],
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRw1nIdsy0x54BHm997GIZOCYxTQ6EzJdIWOgo4TfC78A&s"
  },
  {
    id: 38,
    name: "Tas Hobo Soft Beige Wanita",
    category: "tas",
    gender: "Wanita",
    price: 349000,
    stock: 13,
    description: "Tas hobo soft warna beige dengan bentuk fleksibel dan desain minimalis. Ruangnya cukup untuk membawa kebutuhan utama saat bepergian.",
    color: "Beige",
    size: ["All Size"],
    image: ""
  },
  {
    id: 39,
    name: "Piyama Flannel Kotak Navy Pria",
    category: "piyama",
    gender: "Pria",
    price: 219000,
    stock: 17,
    description: "Set piyama flannel motif kotak navy dengan bahan lembut dan hangat. Cocok untuk tidur atau bersantai di rumah ketika cuaca sejuk.",
    color: "Navy",
    size: ["M", "L", "XL", "XXL"],
    image: ""
  },
  {
    id: 40,
    name: "Kaos Rib Cotton Mauve Wanita",
    category: "kaos",
    gender: "Wanita",
    price: 129000,
    stock: 30,
    description: "Kaos rib cotton warna mauve dengan tekstur bergaris halus dan bahan elastis. Cocok digunakan sebagai atasan utama maupun inner.",
    color: "Mauve",
    size: ["S", "M", "L", "XL"],
    image: ""
  },
  {
    id: 41,
    name: "Kemeja Oxford Oversize Olive Pria",
    category: "kemeja",
    gender: "Pria",
    price: 289000,
    stock: 23,
    description: "Kemeja Oxford oversize warna olive dengan potongan longgar dan kerah klasik. Cocok untuk gaya kasual modern maupun sebagai outer.",
    color: "Olive",
    size: ["M", "L", "XL", "XXL"],
    image: ""
  },
  {
    id: 42,
    name: "Sepatu Loafers Square Toe Tan Wanita",
    category: "sepatu",
    gender: "Wanita",
    price: 359000,
    stock: 17,
    description: "Loafers square toe warna tan dengan bentuk ujung persegi dan desain modern. Cocok untuk outfit kantor, kuliah, maupun acara semi-formal.",
    color: "Tan",
    size: ["36", "37", "38", "39", "40"],
    image: ""
  },
  {
    id: 43,
    name: "Hoodie Oversize Washed Green Pria",
    category: "hoodie",
    gender: "Pria",
    price: 329000,
    stock: 20,
    description: "Hoodie oversize washed green dengan tampilan sedikit washed dan potongan longgar. Cocok untuk gaya streetwear dan aktivitas santai.",
    color: "Washed Green",
    size: ["M", "L", "XL", "XXL"],
    image: ""
  },
  {
    id: 44,
    name: "Kebaya Modern Velvet Maroon",
    category: "kebaya",
    gender: "Wanita",
    price: 825000,
    stock: 8,
    description: "Kebaya modern berbahan velvet warna maroon dengan tampilan mewah dan elegan. Cocok untuk acara malam, pesta, pernikahan, dan acara resmi.",
    color: "Maroon",
    size: ["S", "M", "L", "XL"],
    image: ""
  },
  {
    id: 45,
    name: "Sweater Quarter Zip Hitam Pria",
    category: "sweater",
    gender: "Pria",
    price: 349000,
    stock: 18,
    description: "Sweater quarter zip warna hitam dengan resleting pendek pada bagian kerah. Desain sporty dan rapi untuk gaya kasual pria.",
    color: "Hitam",
    size: ["M", "L", "XL", "XXL"],
    image: ""
  },
  {
    id: 46,
    name: "Tas Mini Shoulder Chain Hitam Wanita",
    category: "tas",
    gender: "Wanita",
    price: 289000,
    stock: 21,
    description: "Tas mini shoulder warna hitam dengan detail rantai pada tali. Ukurannya compact dan cocok untuk membawa barang penting saat menghadiri acara.",
    color: "Hitam",
    size: ["All Size"],
    image: ""
  },
  {
    id: 47,
    name: "Piyama Jersey Sporty Hitam Pria",
    category: "piyama",
    gender: "Pria",
    price: 169000,
    stock: 31,
    description: "Set piyama jersey warna hitam dengan bahan ringan dan elastis. Desain sporty cocok digunakan untuk tidur maupun bersantai di rumah.",
    color: "Hitam",
    size: ["M", "L", "XL", "XXL"],
    image: ""
  },
  {
    id: 48,
    name: "Kaos V-Neck Basic Putih Wanita",
    category: "kaos",
    gender: "Wanita",
    price: 119000,
    stock: 40,
    description: "Kaos V-neck basic warna putih berbahan cotton lembut dengan potongan nyaman. Cocok sebagai atasan sehari-hari atau inner berbagai outfit.",
    color: "Putih",
    size: ["S", "M", "L", "XL"],
    image: ""
  },
  {
    id: 49,
    name: "Kemeja Satin Relaxed Cream Wanita",
    category: "kemeja",
    gender: "Wanita",
    price: 279000,
    stock: 15,
    description: "Kemeja satin relaxed warna cream dengan permukaan halus dan jatuh yang elegan. Cocok untuk gaya kasual, dinner, maupun acara semi-formal.",
    color: "Cream",
    size: ["S", "M", "L", "XL"],
    image: ""
  },
  {
    id: 50,
    name: "Sepatu Derby Kulit Hitam Pria",
    category: "sepatu",
    gender: "Pria",
    price: 629000,
    stock: 10,
    description: "Sepatu derby berbahan kulit warna hitam dengan desain formal klasik. Cocok digunakan bersama celana bahan untuk bekerja atau acara resmi.",
    color: "Hitam",
    size: ["39", "40", "41", "42", "43"],
    image: ""
  },

  {
    id: 51,
    name: "Hoodie Crop Zip Cream Wanita",
    category: "hoodie",
    gender: "Wanita",
    price: 299000,
    stock: 21,
    description: "Hoodie crop zip warna cream dengan bukaan resleting depan dan potongan pendek yang modern. Cocok untuk gaya kasual dengan celana high waist.",
    color: "Cream",
    size: ["S", "M", "L", "XL"],
    image: ""
  },
  {
    id: 52,
    name: "Sweater Mock Neck Abu-abu Pria",
    category: "sweater",
    gender: "Pria",
    price: 319000,
    stock: 17,
    description: "Sweater mock neck warna abu-abu dengan kerah tinggi dan bahan rajut lembut. Cocok untuk tampilan kasual yang lebih rapi saat cuaca dingin.",
    color: "Abu-abu",
    size: ["M", "L", "XL", "XXL"],
    image: ""
  },
  {
    id: 53,
    name: "Tas Bucket Bag Brown Wanita",
    category: "tas",
    gender: "Wanita",
    price: 359000,
    stock: 16,
    description: "Bucket bag warna brown dengan bentuk fleksibel dan desain modern. Memiliki ruang cukup untuk membawa kebutuhan harian wanita.",
    color: "Brown",
    size: ["All Size"],
    image: ""
  },
  {
    id: 54,
    name: "Kaos Heavy Cotton Hitam Pria",
    category: "kaos",
    gender: "Pria",
    price: 169000,
    stock: 33,
    description: "Kaos heavy cotton warna hitam dengan bahan lebih tebal dan kokoh. Potongan regular membuatnya nyaman untuk gaya kasual sehari-hari.",
    color: "Hitam",
    size: ["M", "L", "XL", "XXL"],
    image: ""
  },
  {
    id: 55,
    name: "Kebaya Brokat Floral Soft Pink",
    category: "kebaya",
    gender: "Wanita",
    price: 695000,
    stock: 13,
    description: "Kebaya brokat motif floral warna soft pink dengan detail bunga yang feminin. Cocok untuk acara keluarga, lamaran, wisuda, dan perayaan formal.",
    color: "Soft Pink",
    size: ["S", "M", "L", "XL"],
    image: ""
  },
  {
    id: 56,
    name: "Kemeja Linen Cuban Collar Beige Pria",
    category: "kemeja",
    gender: "Pria",
    price: 279000,
    stock: 23,
    description: "Kemeja linen dengan Cuban collar warna beige dan potongan santai. Bahannya ringan sehingga cocok digunakan untuk liburan dan aktivitas kasual.",
    color: "Beige",
    size: ["M", "L", "XL", "XXL"],
    image: ""
  },
  {
    id: 57,
    name: "Sepatu Platform Sneakers Cream Wanita",
    category: "sepatu",
    gender: "Wanita",
    price: 429000,
    stock: 18,
    description: "Platform sneakers warna cream dengan sol sedikit tinggi dan desain minimalis. Cocok untuk gaya kasual, jalan-jalan, dan aktivitas sehari-hari.",
    color: "Cream",
    size: ["36", "37", "38", "39", "40"],
    image: ""
  },
  {
    id: 58,
    name: "Piyama Katun Polkadot Pink Wanita",
    category: "piyama",
    gender: "Wanita",
    price: 189000,
    stock: 28,
    description: "Set piyama katun motif polkadot warna pink dengan bahan ringan dan lembut. Desainnya nyaman digunakan untuk tidur dan bersantai.",
    color: "Pink",
    size: ["S", "M", "L", "XL"],
    image: ""
  },
  {
    id: 59,
    name: "Hoodie Varsity Navy Pria",
    category: "hoodie",
    gender: "Pria",
    price: 349000,
    stock: 19,
    description: "Hoodie varsity warna navy dengan detail sporty dan potongan relaxed fit. Cocok untuk gaya streetwear dan aktivitas santai sehari-hari.",
    color: "Navy",
    size: ["M", "L", "XL", "XXL"],
    image: ""
  },
  {
    id: 60,
    name: "Sweater Cardigan Dusty Pink Wanita",
    category: "sweater",
    gender: "Wanita",
    price: 339000,
    stock: 15,
    description: "Cardigan knit warna dusty pink dengan kancing depan dan tekstur rajut lembut. Cocok sebagai outer ringan untuk berbagai outfit wanita.",
    color: "Dusty Pink",
    size: ["S", "M", "L", "XL"],
    image: ""
  },
  {
    id: 61,
    name: "Tas Messenger Compact Black Pria",
    category: "tas",
    gender: "Pria",
    price: 249000,
    stock: 24,
    description: "Tas messenger compact warna hitam dengan beberapa kompartemen untuk menyimpan barang kecil. Cocok digunakan untuk aktivitas kerja, kuliah, dan perjalanan.",
    color: "Black",
    size: ["All Size"],
    image: ""
  },
  {
    id: 62,
    name: "Kaos Boxy Crop Lavender Wanita",
    category: "kaos",
    gender: "Wanita",
    price: 139000,
    stock: 27,
    description: "Kaos boxy crop warna lavender dengan potongan pendek dan lebar yang modern. Cocok dipadukan dengan celana atau rok high waist.",
    color: "Lavender",
    size: ["S", "M", "L", "XL"],
    image: ""
  },
  {
    id: 63,
    name: "Kebaya Kutubaru Brokat Burgundy",
    category: "kebaya",
    gender: "Wanita",
    price: 785000,
    stock: 9,
    description: "Kebaya kutubaru berbahan brokat warna burgundy dengan tampilan elegan dan klasik. Cocok untuk acara adat, keluarga, dan perayaan formal.",
    color: "Burgundy",
    size: ["S", "M", "L", "XL"],
    image: ""
  },
  {
    id: 64,
    name: "Kemeja Flannel Check Green Pria",
    category: "kemeja",
    gender: "Pria",
    price: 229000,
    stock: 31,
    description: "Kemeja flannel motif check warna hijau dengan bahan lembut dan nyaman. Bisa digunakan sebagai kemeja maupun outer untuk gaya kasual.",
    color: "Green",
    size: ["M", "L", "XL", "XXL"],
    image: ""
  },
  {
    id: 65,
    name: "Sepatu Canvas High Top Hitam Pria",
    category: "sepatu",
    gender: "Pria",
    price: 319000,
    stock: 26,
    description: "Sepatu canvas high top warna hitam dengan desain klasik dan bagian atas menutupi pergelangan kaki. Cocok untuk gaya kasual dan streetwear.",
    color: "Hitam",
    size: ["39", "40", "41", "42", "43"],
    image: ""
  },
  {
    id: 66,
    name: "Piyama Homewear Rayon Dusty Blue Wanita",
    category: "piyama",
    gender: "Wanita",
    price: 209000,
    stock: 18,
    description: "Set homewear rayon warna dusty blue dengan bahan ringan dan lembut. Potongannya santai sehingga nyaman untuk tidur maupun beraktivitas di rumah.",
    color: "Dusty Blue",
    size: ["S", "M", "L", "XL"],
    image: ""
  },
  {
    id: 67,
    name: "Hoodie Fleece Oversize Mauve Wanita",
    category: "hoodie",
    gender: "Wanita",
    price: 329000,
    stock: 18,
    description: "Hoodie fleece oversize warna mauve dengan bahan lembut dan hangat. Potongan longgar memberikan tampilan kasual yang nyaman untuk sehari-hari.",
    color: "Mauve",
    size: ["S", "M", "L", "XL"],
    image: ""
  },
  {
    id: 68,
    name: "Sweater Knit Polo Collar Olive Pria",
    category: "sweater",
    gender: "Pria",
    price: 329000,
    stock: 13,
    description: "Sweater knit dengan kerah polo warna olive dan tekstur rajut halus. Cocok untuk tampilan smart casual maupun gaya santai.",
    color: "Olive",
    size: ["M", "L", "XL", "XXL"],
    image: ""
  },
  {
    id: 69,
    name: "Tas Ransel Mini Nylon Sage Wanita",
    category: "tas",
    gender: "Wanita",
    price: 239000,
    stock: 19,
    description: "Tas ransel mini berbahan nylon warna sage dengan ukuran compact dan ringan. Cocok untuk jalan-jalan, kuliah, maupun aktivitas sehari-hari.",
    color: "Sage",
    size: ["All Size"],
    image: ""
  },
  {
    id: 70,
    name: "Kaos Striped Cotton Navy Pria",
    category: "kaos",
    gender: "Pria",
    price: 149000,
    stock: 36,
    description: "Kaos cotton motif garis warna navy dengan potongan regular fit. Memberikan tampilan kasual klasik yang mudah dipadukan dengan berbagai bawahan.",
    color: "Navy",
    size: ["M", "L", "XL", "XXL"],
    image: ""
  },

  {
    id: 71,
    name: "Kemeja Denim Light Blue Wanita",
    category: "kemeja",
    gender: "Wanita",
    price: 299000,
    stock: 18,
    description: "Kemeja denim warna light blue dengan bahan denim ringan dan desain kasual. Bisa dipakai sebagai kemeja utama maupun outer.",
    color: "Light Blue",
    size: ["S", "M", "L", "XL"],
    image: ""
  },
  {
    id: 72,
    name: "Sepatu Ballet Flat Nude Wanita",
    category: "sepatu",
    gender: "Wanita",
    price: 259000,
    stock: 24,
    description: "Sepatu ballet flat warna nude dengan bentuk sederhana dan feminin. Cocok dipadukan dengan dress, rok, maupun celana untuk aktivitas harian.",
    color: "Nude",
    size: ["36", "37", "38", "39", "40"],
    image: ""
  },
  {
    id: 73,
    name: "Piyama Modal Soft Grey Pria",
    category: "piyama",
    gender: "Pria",
    price: 209000,
    stock: 23,
    description: "Set piyama modal warna grey dengan bahan lembut dan ringan. Desain relaxed fit memberikan kenyamanan saat tidur maupun bersantai.",
    color: "Grey",
    size: ["M", "L", "XL", "XXL"],
    image: ""
  },
  {
    id: 74,
    name: "Hoodie Basic Oversize Lilac Wanita",
    category: "hoodie",
    gender: "Wanita",
    price: 299000,
    stock: 24,
    description: "Hoodie basic oversize warna lilac dengan bahan lembut dan potongan longgar. Cocok untuk gaya kasual, kuliah, dan aktivitas santai.",
    color: "Lilac",
    size: ["S", "M", "L", "XL"],
    image: ""
  },
  {
    id: 75,
    name: "Sweater Crewneck Fleece Navy Pria",
    category: "sweater",
    gender: "Pria",
    price: 279000,
    stock: 25,
    description: "Sweater crewneck berbahan fleece warna navy dengan tekstur lembut dan hangat. Cocok untuk digunakan saat cuaca sejuk dan aktivitas santai.",
    color: "Navy",
    size: ["M", "L", "XL", "XXL"],
    image: ""
  },
  {
    id: 76,
    name: "Kebaya Modern Lace Ivory",
    category: "kebaya",
    gender: "Wanita",
    price: 765000,
    stock: 9,
    description: "Kebaya modern berbahan lace warna ivory dengan detail halus dan tampilan feminin. Cocok untuk acara keluarga, pernikahan, wisuda, dan acara formal.",
    color: "Ivory",
    size: ["S", "M", "L", "XL"],
    image: ""
  },
  {
    id: 77,
    name: "Tas Tote Structured Cream Wanita",
    category: "tas",
    gender: "Wanita",
    price: 379000,
    stock: 14,
    description: "Tas tote structured warna cream dengan bentuk kokoh dan ruang penyimpanan luas. Cocok untuk bekerja, kuliah, maupun kegiatan sehari-hari.",
    color: "Cream",
    size: ["All Size"],
    image: ""
  },
  {
    id: 78,
    name: "Kaos Graphic Vintage Brown Pria",
    category: "kaos",
    gender: "Pria",
    price: 159000,
    stock: 35,
    description: "Kaos graphic vintage warna brown dengan desain bernuansa retro dan bahan cotton nyaman. Cocok untuk gaya kasual dan streetwear.",
    color: "Brown",
    size: ["M", "L", "XL", "XXL"],
    image: ""
  },
  {
    id: 79,
    name: "Kemeja Corduroy Overshirt Camel Pria",
    category: "kemeja",
    gender: "Pria",
    price: 339000,
    stock: 18,
    description: "Kemeja overshirt corduroy warna camel dengan tekstur khas dan potongan relaxed. Cocok sebagai outer untuk gaya kasual dan layering.",
    color: "Camel",
    size: ["M", "L", "XL", "XXL"],
    image: ""
  },
  {
    id: 80,
    name: "Sepatu Sneakers Retro Beige Pria",
    category: "sepatu",
    gender: "Pria",
    price: 429000,
    stock: 19,
    description: "Sneakers retro warna beige dengan desain terinspirasi gaya klasik. Memiliki sol nyaman untuk berjalan dan cocok digunakan sehari-hari.",
    color: "Beige",
    size: ["39", "40", "41", "42", "43"],
    image: ""
  },

  {
    id: 81,
    name: "Piyama Katun Stripe Blue Pria",
    category: "piyama",
    gender: "Pria",
    price: 179000,
    stock: 29,
    description: "Set piyama katun motif stripe warna blue dengan bahan ringan dan nyaman. Cocok digunakan untuk tidur dan bersantai di rumah.",
    color: "Blue",
    size: ["M", "L", "XL", "XXL"],
    image: ""
  },
  {
    id: 82,
    name: "Hoodie Zip Fleece Beige Wanita",
    category: "hoodie",
    gender: "Wanita",
    price: 319000,
    stock: 26,
    description: "Hoodie zip fleece warna beige dengan bahan hangat dan lembut. Dilengkapi resleting depan dan cocok untuk gaya kasual sehari-hari.",
    color: "Beige",
    size: ["S", "M", "L", "XL"],
    image: ""
  },
  {
    id: 83,
    name: "Sweater Turtleneck Knit Cream Wanita",
    category: "sweater",
    gender: "Wanita",
    price: 359000,
    stock: 12,
    description: "Sweater turtleneck knit warna cream dengan kerah tinggi dan bahan hangat. Cocok untuk tampilan elegan dan nyaman saat cuaca dingin.",
    color: "Cream",
    size: ["S", "M", "L", "XL"],
    image: ""
  },
  {
    id: 84,
    name: "Tas Crossbody Leather Brown Pria",
    category: "tas",
    gender: "Pria",
    price: 399000,
    stock: 11,
    description: "Tas crossbody berbahan kulit warna brown dengan desain klasik dan kompartemen praktis. Cocok untuk membawa barang penting saat bepergian.",
    color: "Brown",
    size: ["All Size"],
    image: ""
  },
  {
    id: 85,
    name: "Kaos Boxy Basic Sage Wanita",
    category: "kaos",
    gender: "Wanita",
    price: 139000,
    stock: 36,
    description: "Kaos boxy basic warna sage dengan potongan sedikit lebar dan bahan cotton lembut. Cocok untuk gaya kasual dan outfit sehari-hari.",
    color: "Sage",
    size: ["S", "M", "L", "XL"],
    image: ""
  },
  {
    id: 86,
    name: "Kebaya Brokat Sequin Emerald",
    category: "kebaya",
    gender: "Wanita",
    price: 925000,
    stock: 6,
    description: "Kebaya brokat warna emerald dengan detail sequin yang memberikan kesan mewah. Cocok untuk pesta, pernikahan, dan acara formal malam.",
    color: "Emerald",
    size: ["S", "M", "L", "XL"],
    image: ""
  },
  {
    id: 87,
    name: "Kemeja Oxford Slim Fit Biru Pria",
    category: "kemeja",
    gender: "Pria",
    price: 319000,
    stock: 20,
    description: "Kemeja Oxford slim fit warna biru dengan kerah klasik dan kancing depan. Cocok untuk bekerja, kuliah, dan gaya smart casual.",
    color: "Biru",
    size: ["S", "M", "L", "XL"],
    image: ""
  },
  {
    id: 88,
    name: "Sepatu Running Lightweight Black Pria",
    category: "sepatu",
    gender: "Pria",
    price: 419000,
    stock: 20,
    description: "Sepatu running lightweight warna hitam dengan konstruksi ringan dan desain breathable. Cocok untuk jogging, olahraga ringan, dan aktivitas harian.",
    color: "Black",
    size: ["39", "40", "41", "42", "43"],
    image: ""
  },
  {
    id: 89,
    name: "Piyama Rayon Motif Daun Olive Wanita",
    category: "piyama",
    gender: "Wanita",
    price: 219000,
    stock: 20,
    description: "Set piyama rayon motif daun warna olive dengan bahan ringan dan lembut. Memberikan kenyamanan saat tidur maupun bersantai di rumah.",
    color: "Olive",
    size: ["S", "M", "L", "XL"],
    image: ""
  },
  {
    id: 90,
    name: "Hoodie Pullover French Terry Abu-abu Pria",
    category: "hoodie",
    gender: "Pria",
    price: 299000,
    stock: 30,
    description: "Hoodie pullover French terry warna abu-abu dengan bahan nyaman dan potongan santai. Cocok untuk gaya kasual dan aktivitas sehari-hari.",
    color: "Abu-abu",
    size: ["M", "L", "XL", "XXL"],
    image: ""
  },

  {
    id: 91,
    name: "Sweater Cardigan Button Cream Wanita",
    category: "sweater",
    gender: "Wanita",
    price: 319000,
    stock: 14,
    description: "Cardigan sweater warna cream dengan kancing depan dan bahan rajut lembut. Cocok sebagai outer ringan untuk outfit kasual maupun semi-formal.",
    color: "Cream",
    size: ["S", "M", "L", "XL"],
    image: ""
  },
  {
    id: 92,
    name: "Tas Backpack Urban Black Pria",
    category: "tas",
    gender: "Pria",
    price: 329000,
    stock: 18,
    description: "Tas backpack urban warna hitam dengan beberapa kompartemen untuk menyimpan laptop, buku, dan perlengkapan harian. Cocok untuk kerja dan kuliah.",
    color: "Black",
    size: ["All Size"],
    image: ""
  },
  {
    id: 93,
    name: "Kaos Polo Pique Hitam Pria",
    category: "kaos",
    gender: "Pria",
    price: 189000,
    stock: 34,
    description: "Kaos polo berbahan pique warna hitam dengan kerah klasik dan dua kancing depan. Memberikan tampilan kasual yang lebih rapi.",
    color: "Hitam",
    size: ["M", "L", "XL", "XXL"],
    image: ""
  },
  {
    id: 94,
    name: "Kebaya Peplum Brokat Mauve",
    category: "kebaya",
    gender: "Wanita",
    price: 735000,
    stock: 10,
    description: "Kebaya peplum berbahan brokat warna mauve dengan potongan feminin dan detail elegan. Cocok untuk acara keluarga, lamaran, dan perayaan formal.",
    color: "Mauve",
    size: ["S", "M", "L", "XL"],
    image: ""
  },
  {
    id: 95,
    name: "Kemeja Satin Oversize Sage Wanita",
    category: "kemeja",
    gender: "Wanita",
    price: 299000,
    stock: 16,
    description: "Kemeja satin oversize warna sage dengan permukaan halus dan potongan longgar. Cocok untuk gaya kasual modern maupun acara semi-formal.",
    color: "Sage",
    size: ["S", "M", "L", "XL"],
    image: ""
  },
  {
    id: 96,
    name: "Sepatu Canvas Low Cut Putih Pria",
    category: "sepatu",
    gender: "Pria",
    price: 279000,
    stock: 30,
    description: "Sepatu canvas low cut warna putih dengan desain klasik dan sol fleksibel. Cocok untuk gaya kasual, kuliah, jalan-jalan, dan aktivitas sehari-hari.",
    color: "Putih",
    size: ["39", "40", "41", "42", "43"],
    image: ""
  },
  {
    id: 97,
    name: "Piyama Homewear Katun Cream Wanita",
    category: "piyama",
    gender: "Wanita",
    price: 179000,
    stock: 34,
    description: "Set homewear katun warna cream dengan potongan longgar dan bahan lembut. Nyaman digunakan untuk tidur, bersantai, dan aktivitas ringan di rumah.",
    color: "Cream",
    size: ["S", "M", "L", "XL"],
    image: ""
  },
  {
    id: 98,
    name: "Hoodie Varsity Cream Pria",
    category: "hoodie",
    gender: "Pria",
    price: 339000,
    stock: 17,
    description: "Hoodie varsity warna cream dengan detail sporty dan potongan relaxed fit. Cocok untuk gaya streetwear dan aktivitas kasual pria.",
    color: "Cream",
    size: ["M", "L", "XL", "XXL"],
    image: ""
  },
  {
    id: 99,
    name: "Sweater Knit Cable Cokelat Wanita",
    category: "sweater",
    gender: "Wanita",
    price: 329000,
    stock: 16,
    description: "Sweater knit cable warna cokelat dengan tekstur rajutan klasik dan bahan hangat. Cocok untuk gaya kasual saat cuaca sejuk.",
    color: "Cokelat",
    size: ["S", "M", "L", "XL"],
    image: ""
  },
  {
    id: 100,
    name: "Tas Mini Top Handle Cream Wanita",
    category: "tas",
    gender: "Wanita",
    price: 319000,
    stock: 15,
    description: "Tas mini top handle warna cream dengan bentuk rapi dan elegan. Ukurannya cocok untuk membawa barang penting saat menghadiri acara atau bepergian.",
    color: "Cream",
    size: ["All Size"],
    image: ""
  },

  {
    id: 101,
    name: "Kaos Basic Regular Fit Abu-abu Pria",
    category: "kaos",
    gender: "Pria",
    price: 119000,
    stock: 42,
    description: "Kaos basic regular fit warna abu-abu berbahan cotton yang nyaman. Desain minimalis membuatnya mudah dipadukan dengan berbagai celana.",
    color: "Abu-abu",
    size: ["M", "L", "XL", "XXL"],
    image: ""
  },
  {
    id: 102,
    name: "Kemeja Poplin Relaxed Blue Wanita",
    category: "kemeja",
    gender: "Wanita",
    price: 249000,
    stock: 19,
    description: "Kemeja poplin relaxed warna biru dengan bahan ringan dan potongan santai. Cocok untuk gaya kasual, kerja, maupun kuliah.",
    color: "Biru",
    size: ["S", "M", "L", "XL"],
    image: ""
  },
  {
    id: 103,
    name: "Sepatu Slip On Canvas Navy Pria",
    category: "sepatu",
    gender: "Pria",
    price: 269000,
    stock: 32,
    description: "Sepatu slip on canvas warna navy dengan desain tanpa tali yang praktis. Cocok digunakan untuk aktivitas santai dan perjalanan sehari-hari.",
    color: "Navy",
    size: ["39", "40", "41", "42", "43"],
    image: ""
  },
  {
    id: 104,
    name: "Piyama Satin Floral Champagne Wanita",
    category: "piyama",
    gender: "Wanita",
    price: 249000,
    stock: 16,
    description: "Set piyama satin motif floral warna champagne dengan bahan halus dan tampilan elegan. Cocok untuk tidur maupun bersantai dengan nyaman.",
    color: "Champagne",
    size: ["S", "M", "L", "XL"],
    image: ""
  },
  {
    id: 105,
    name: "Hoodie Basic French Terry Black Pria",
    category: "hoodie",
    gender: "Pria",
    price: 309000,
    stock: 23,
    description: "Hoodie basic berbahan French terry warna hitam dengan desain minimalis dan potongan santai. Cocok untuk gaya kasual dan streetwear.",
    color: "Black",
    size: ["M", "L", "XL", "XXL"],
    image: ""
  },
  {
    id: 106,
    name: "Sweater Knit Striped Cream Wanita",
    category: "sweater",
    gender: "Wanita",
    price: 309000,
    stock: 18,
    description: "Sweater knit motif garis warna cream dengan tekstur rajut lembut. Cocok digunakan sebagai atasan hangat untuk gaya kasual wanita.",
    color: "Cream",
    size: ["S", "M", "L", "XL"],
    image: ""
  },
  {
    id: 107,
    name: "Tas Tote Structured Black Pria",
    category: "tas",
    gender: "Pria",
    price: 349000,
    stock: 14,
    description: "Tas tote structured warna hitam dengan bentuk kokoh dan ruang cukup luas. Cocok untuk membawa laptop, dokumen, dan perlengkapan kerja.",
    color: "Black",
    size: ["All Size"],
    image: ""
  },
  {
    id: 108,
    name: "Kaos Oversize Pocket Cream Pria",
    category: "kaos",
    gender: "Pria",
    price: 139000,
    stock: 38,
    description: "Kaos oversize warna cream dengan detail pocket pada bagian dada dan bahan cotton lembut. Cocok untuk gaya kasual dan streetwear.",
    color: "Cream",
    size: ["M", "L", "XL", "XXL"],
    image: ""
  },
  {
    id: 109,
    name: "Kebaya Brokat Floral Dusty Rose",
    category: "kebaya",
    gender: "Wanita",
    price: 795000,
    stock: 8,
    description: "Kebaya brokat motif floral warna dusty rose dengan detail bunga yang lembut. Cocok untuk acara keluarga, lamaran, wisuda, dan pesta formal.",
    color: "Dusty Rose",
    size: ["S", "M", "L", "XL"],
    image: ""
  },
  {
    id: 110,
    name: "Kemeja Oxford Stripe Blue Pria",
    category: "kemeja",
    gender: "Pria",
    price: 309000,
    stock: 25,
    description: "Kemeja Oxford motif stripe warna blue dengan kerah klasik dan potongan rapi. Cocok untuk kerja, kuliah, dan tampilan smart casual.",
    color: "Blue",
    size: ["S", "M", "L", "XL"],
    image: ""
  },
  {
    id: 111,
    name: "Sepatu Mary Jane Strap Cream Wanita",
    category: "sepatu",
    gender: "Wanita",
    price: 329000,
    stock: 19,
    description: "Sepatu Mary Jane warna cream dengan strap pada bagian atas dan desain feminin. Cocok digunakan bersama dress, rok, maupun celana.",
    color: "Cream",
    size: ["36", "37", "38", "39", "40"],
    image: ""
  },
  {
    id: 112,
    name: "Piyama Modal Relaxed Navy Pria",
    category: "piyama",
    gender: "Pria",
    price: 219000,
    stock: 21,
    description: "Set piyama modal relaxed warna navy dengan bahan lembut dan ringan. Potongan santai memberikan kenyamanan saat tidur dan bersantai.",
    color: "Navy",
    size: ["M", "L", "XL", "XXL"],
    image: ""
  },
  {
    id: 113,
    name: "Hoodie Minimalist Sage Wanita",
    category: "hoodie",
    gender: "Wanita",
    price: 289000,
    stock: 27,
    description: "Hoodie minimalist warna sage dengan desain polos dan bahan fleece lembut. Cocok untuk gaya kasual yang sederhana dan nyaman.",
    color: "Sage",
    size: ["S", "M", "L", "XL"],
    image: ""
  },
  {
    id: 114,
    name: "Sweater Crewneck Charcoal Pria",
    category: "sweater",
    gender: "Pria",
    price: 269000,
    stock: 28,
    description: "Sweater crewneck warna charcoal dengan desain polos dan bahan lembut. Cocok dipakai bersama jeans atau chino untuk gaya kasual.",
    color: "Charcoal",
    size: ["M", "L", "XL", "XXL"],
    image: ""
  },
  {
    id: 115,
    name: "Tas Shoulder Soft Pink Wanita",
    category: "tas",
    gender: "Wanita",
    price: 299000,
    stock: 19,
    description: "Tas shoulder warna soft pink dengan desain feminin dan ukuran praktis. Cocok untuk membawa ponsel, dompet, makeup, dan barang kecil.",
    color: "Soft Pink",
    size: ["All Size"],
    image: ""
  },
  {
    id: 116,
    name: "Kaos Polo Cotton Maroon Pria",
    category: "kaos",
    gender: "Pria",
    price: 179000,
    stock: 30,
    description: "Kaos polo cotton warna maroon dengan kerah klasik dan kancing depan. Cocok untuk gaya kasual yang lebih rapi.",
    color: "Maroon",
    size: ["M", "L", "XL", "XXL"],
    image: ""
  },
  {
    id: 117,
    name: "Kemeja Linen Puff Sleeve Beige Wanita",
    category: "kemeja",
    gender: "Wanita",
    price: 289000,
    stock: 17,
    description: "Kemeja linen warna beige dengan detail puff sleeve dan bahan ringan. Cocok untuk gaya feminin, santai, maupun semi-formal.",
    color: "Beige",
    size: ["S", "M", "L", "XL"],
    image: ""
  },
  {
    id: 118,
    name: "Kebaya Modern Bordir Sage Green",
    category: "kebaya",
    gender: "Wanita",
    price: 725000,
    stock: 10,
    description: "Kebaya modern warna sage green dengan detail bordir yang elegan. Cocok untuk acara keluarga, wisuda, lamaran, dan perayaan formal.",
    color: "Sage Green",
    size: ["S", "M", "L", "XL"],
    image: ""
  },
  {
    id: 119,
    name: "Sepatu Sneakers Casual Beige Wanita",
    category: "sepatu",
    gender: "Wanita",
    price: 399000,
    stock: 22,
    description: "Sneakers casual warna beige dengan desain minimalis dan sol nyaman. Cocok digunakan untuk jalan-jalan, kuliah, dan aktivitas sehari-hari.",
    color: "Beige",
    size: ["36", "37", "38", "39", "40"],
    image: ""
  },
  {
    id: 120,
    name: "Piyama Rayon Motif Floral Pink Wanita",
    category: "piyama",
    gender: "Wanita",
    price: 219000,
    stock: 24,
    description: "Set piyama rayon motif floral warna pink dengan bahan ringan dan lembut. Cocok untuk tidur dan bersantai dengan tampilan feminin.",
    color: "Pink",
    size: ["S", "M", "L", "XL"],
    image: ""
  },
  {
    id: 121,
    name: "Kemeja Flannel Kotak Navy Wanita",
    category: "kemeja",
    gender: "Wanita",
    price: 239000,
    stock: 26,
    description: "Kemeja flannel motif kotak warna navy dengan bahan lembut dan nyaman. Potongannya santai sehingga cocok digunakan sebagai atasan maupun outer.",
    color: "Navy",
    size: ["S", "M", "L", "XL"],
    image: ""
  },
  {
    id: 122,
    name: "Hoodie Pullover Cream Pria",
    category: "hoodie",
    gender: "Pria",
    price: 299000,
    stock: 24,
    description: "Hoodie pullover warna cream dengan bahan fleece lembut dan hangat. Memiliki desain minimalis yang mudah dipadukan dengan jeans maupun jogger.",
    color: "Cream",
    size: ["M", "L", "XL", "XXL"],
    image: ""
  },
  {
    id: 123,
    name: "Sepatu Running Mesh Pink Wanita",
    category: "sepatu",
    gender: "Wanita",
    price: 389000,
    stock: 21,
    description: "Sepatu running berbahan mesh warna pink dengan desain ringan dan breathable. Cocok untuk jogging, olahraga ringan, dan aktivitas sehari-hari.",
    color: "Pink",
    size: ["36", "37", "38", "39", "40"],
    image: ""
  },
  {
    id: 124,
    name: "Piyama Satin Emerald Wanita",
    category: "piyama",
    gender: "Wanita",
    price: 259000,
    stock: 15,
    description: "Set piyama satin warna emerald dengan bahan halus dan tampilan elegan. Terdiri dari atasan berkancing dan celana panjang yang nyaman.",
    color: "Emerald",
    size: ["S", "M", "L", "XL"],
    image: ""
  },
  {
    id: 125,
    name: "Tas Sling Bag Nylon Black Pria",
    category: "tas",
    gender: "Pria",
    price: 189000,
    stock: 29,
    description: "Tas sling bag berbahan nylon warna hitam dengan desain ringan dan praktis. Memiliki kompartemen untuk menyimpan ponsel, dompet, kunci, dan barang kecil.",
    color: "Black",
    size: ["All Size"],
    image: ""
  },
  {
    id: 126,
    name: "Sweater Knit V-Neck Beige Wanita",
    category: "sweater",
    gender: "Wanita",
    price: 299000,
    stock: 18,
    description: "Sweater knit V-neck warna beige dengan tekstur rajut lembut dan potongan regular. Cocok dipakai dengan jeans, rok, maupun celana bahan.",
    color: "Beige",
    size: ["S", "M", "L", "XL"],
    image: ""
  },
  {
    id: 127,
    name: "Kaos Graphic Vintage Cream Pria",
    category: "kaos",
    gender: "Pria",
    price: 159000,
    stock: 37,
    description: "Kaos graphic warna cream dengan desain vintage pada bagian depan dan bahan cotton nyaman. Cocok untuk gaya kasual dan streetwear.",
    color: "Cream",
    size: ["M", "L", "XL", "XXL"],
    image: ""
  },
  {
    id: 128,
    name: "Kebaya Brokat Modern Dusty Blue",
    category: "kebaya",
    gender: "Wanita",
    price: 695000,
    stock: 11,
    description: "Kebaya modern berbahan brokat warna dusty blue dengan detail motif elegan. Cocok untuk wisuda, acara keluarga, lamaran, dan perayaan formal.",
    color: "Dusty Blue",
    size: ["S", "M", "L", "XL"],
    image: ""
  },
  {
    id: 129,
    name: "Kemeja Linen Short Sleeve Olive Pria",
    category: "kemeja",
    gender: "Pria",
    price: 269000,
    stock: 23,
    description: "Kemeja linen lengan pendek warna olive dengan bahan ringan dan nyaman. Cocok untuk liburan, acara santai, dan aktivitas sehari-hari.",
    color: "Olive",
    size: ["M", "L", "XL", "XXL"],
    image: ""
  },
  {
    id: 130,
    name: "Hoodie Oversize Dusty Blue Wanita",
    category: "hoodie",
    gender: "Wanita",
    price: 309000,
    stock: 22,
    description: "Hoodie oversize warna dusty blue dengan bahan fleece lembut dan potongan longgar. Cocok untuk gaya kasual, kuliah, dan aktivitas santai.",
    color: "Dusty Blue",
    size: ["S", "M", "L", "XL"],
    image: ""
  },
  {
    id: 131,
    name: "Sepatu Loafers Leather Tan Pria",
    category: "sepatu",
    gender: "Pria",
    price: 549000,
    stock: 13,
    description: "Loafers berbahan kulit warna tan dengan desain klasik dan tampilan rapi. Cocok digunakan untuk bekerja, acara semi-formal, maupun gaya smart casual.",
    color: "Tan",
    size: ["39", "40", "41", "42", "43"],
    image: ""
  },
  {
    id: 132,
    name: "Piyama Katun Stripe Pink Wanita",
    category: "piyama",
    gender: "Wanita",
    price: 189000,
    stock: 27,
    description: "Set piyama katun motif garis warna pink dengan bahan ringan dan lembut. Nyaman digunakan untuk tidur maupun bersantai di rumah.",
    color: "Pink",
    size: ["S", "M", "L", "XL"],
    image: ""
  },
  {
    id: 133,
    name: "Tas Tote Canvas Black Pria",
    category: "tas",
    gender: "Pria",
    price: 199000,
    stock: 31,
    description: "Tas tote canvas warna hitam dengan desain sederhana dan ruang cukup luas. Cocok untuk membawa buku, laptop, perlengkapan kerja, maupun kebutuhan harian.",
    color: "Black",
    size: ["All Size"],
    image: ""
  },
  {
    id: 134,
    name: "Sweater Crewneck Burgundy Wanita",
    category: "sweater",
    gender: "Wanita",
    price: 279000,
    stock: 20,
    description: "Sweater crewneck warna burgundy dengan bahan lembut dan potongan regular. Cocok untuk tampilan kasual yang hangat dan mudah dipadukan.",
    color: "Burgundy",
    size: ["S", "M", "L", "XL"],
    image: ""
  },
  {
    id: 135,
    name: "Kaos Oversize Washed Black Pria",
    category: "kaos",
    gender: "Pria",
    price: 169000,
    stock: 34,
    description: "Kaos oversize washed black dengan tampilan sedikit pudar dan potongan longgar. Cocok untuk gaya streetwear dan outfit kasual sehari-hari.",
    color: "Washed Black",
    size: ["M", "L", "XL", "XXL"],
    image: ""
  },
  {
    id: 136,
    name: "Kebaya Kutubaru Brokat Navy",
    category: "kebaya",
    gender: "Wanita",
    price: 765000,
    stock: 8,
    description: "Kebaya kutubaru berbahan brokat warna navy dengan desain klasik dan elegan. Cocok untuk acara adat, keluarga, pernikahan, dan acara resmi.",
    color: "Navy",
    size: ["S", "M", "L", "XL"],
    image: ""
  },
  {
    id: 137,
    name: "Kemeja Oxford Regular Fit Cream Pria",
    category: "kemeja",
    gender: "Pria",
    price: 309000,
    stock: 19,
    description: "Kemeja Oxford regular fit warna cream dengan kerah klasik dan kancing depan. Cocok untuk bekerja, kuliah, maupun tampilan smart casual.",
    color: "Cream",
    size: ["S", "M", "L", "XL"],
    image: ""
  },
  {
    id: 138,
    name: "Hoodie Zip Oversize Charcoal Pria",
    category: "hoodie",
    gender: "Pria",
    price: 319000,
    stock: 21,
    description: "Hoodie zip oversize warna charcoal dengan bahan fleece nyaman dan desain minimalis. Cocok untuk streetwear maupun aktivitas santai.",
    color: "Charcoal",
    size: ["M", "L", "XL", "XXL"],
    image: ""
  },
  {
    id: 139,
    name: "Sepatu Ballet Flat Black Wanita",
    category: "sepatu",
    gender: "Wanita",
    price: 249000,
    stock: 28,
    description: "Sepatu ballet flat warna hitam dengan desain sederhana dan feminin. Cocok digunakan untuk kuliah, bekerja, jalan-jalan, maupun acara santai.",
    color: "Black",
    size: ["36", "37", "38", "39", "40"],
    image: ""
  },
  {
    id: 140,
    name: "Piyama Rayon Stripe Sage Wanita",
    category: "piyama",
    gender: "Wanita",
    price: 209000,
    stock: 19,
    description: "Set piyama rayon motif stripe warna sage dengan bahan ringan dan lembut. Potongannya santai sehingga nyaman untuk tidur dan bersantai.",
    color: "Sage",
    size: ["S", "M", "L", "XL"],
    image: ""
  },
  {
    id: 141,
    name: "Tas Crossbody Leather Black Wanita",
    category: "tas",
    gender: "Wanita",
    price: 369000,
    stock: 17,
    description: "Tas crossbody berbahan kulit warna hitam dengan desain elegan dan tali panjang yang dapat disesuaikan. Cocok untuk aktivitas harian maupun acara semi-formal.",
    color: "Black",
    size: ["All Size"],
    image: ""
  },
  {
    id: 142,
    name: "Sweater Half Zip Grey Pria",
    category: "sweater",
    gender: "Pria",
    price: 339000,
    stock: 16,
    description: "Sweater half zip warna grey dengan kerah tinggi dan resleting pendek. Bahannya lembut dan cocok untuk gaya kasual saat cuaca sejuk.",
    color: "Grey",
    size: ["M", "L", "XL", "XXL"],
    image: ""
  },
  {
    id: 143,
    name: "Kaos Ribbed Slim Fit White Wanita",
    category: "kaos",
    gender: "Wanita",
    price: 129000,
    stock: 32,
    description: "Kaos ribbed slim fit warna putih dengan tekstur bergaris halus dan bahan elastis. Cocok digunakan sendiri maupun sebagai inner.",
    color: "White",
    size: ["S", "M", "L", "XL"],
    image: ""
  },
  {
    id: 144,
    name: "Kebaya Modern Brokat Black",
    category: "kebaya",
    gender: "Wanita",
    price: 795000,
    stock: 7,
    description: "Kebaya modern berbahan brokat warna hitam dengan desain elegan dan detail feminin. Cocok untuk pesta, pernikahan, dan acara formal malam.",
    color: "Black",
    size: ["S", "M", "L", "XL"],
    image: ""
  },
  {
    id: 145,
    name: "Kemeja Denim Oversize Blue Wanita",
    category: "kemeja",
    gender: "Wanita",
    price: 319000,
    stock: 18,
    description: "Kemeja denim oversize warna blue dengan potongan longgar dan bahan denim ringan. Cocok dipakai sebagai outer atau kemeja utama.",
    color: "Blue",
    size: ["S", "M", "L", "XL"],
    image: ""
  },
  {
    id: 146,
    name: "Hoodie Graphic Black Wanita",
    category: "hoodie",
    gender: "Wanita",
    price: 319000,
    stock: 24,
    description: "Hoodie graphic warna hitam dengan detail tulisan pada bagian depan dan bahan fleece lembut. Cocok untuk gaya kasual dan streetwear.",
    color: "Black",
    size: ["S", "M", "L", "XL"],
    image: ""
  },
  {
    id: 147,
    name: "Sepatu Sneakers Retro White Green Pria",
    category: "sepatu",
    gender: "Pria",
    price: 449000,
    stock: 16,
    description: "Sneakers retro kombinasi putih dan hijau dengan desain klasik. Memiliki sol nyaman dan cocok digunakan untuk jalan-jalan maupun aktivitas sehari-hari.",
    color: "White Green",
    size: ["39", "40", "41", "42", "43"],
    image: ""
  },
  {
    id: 148,
    name: "Piyama Satin Dusty Rose Wanita",
    category: "piyama",
    gender: "Wanita",
    price: 249000,
    stock: 17,
    description: "Set piyama satin warna dusty rose dengan permukaan halus dan tampilan feminin. Cocok digunakan untuk tidur dan bersantai di rumah.",
    color: "Dusty Rose",
    size: ["S", "M", "L", "XL"],
    image: ""
  },
  {
    id: 149,
    name: "Tas Messenger Canvas Olive Pria",
    category: "tas",
    gender: "Pria",
    price: 229000,
    stock: 26,
    description: "Tas messenger canvas warna olive dengan tali bahu adjustable dan beberapa ruang penyimpanan. Cocok untuk kuliah, kerja, dan aktivitas luar.",
    color: "Olive",
    size: ["All Size"],
    image: ""
  },
  {
    id: 150,
    name: "Sweater Cable Knit Navy Wanita",
    category: "sweater",
    gender: "Wanita",
    price: 329000,
    stock: 14,
    description: "Sweater cable knit warna navy dengan tekstur rajut klasik dan bahan hangat. Cocok untuk gaya kasual maupun outfit saat cuaca dingin.",
    color: "Navy",
    size: ["S", "M", "L", "XL"],
    image: ""
  },

  {
    id: 151,
    name: "Kaos Basic Cotton Beige Pria",
    category: "kaos",
    gender: "Pria",
    price: 119000,
    stock: 43,
    description: "Kaos basic cotton warna beige dengan potongan regular fit dan bahan lembut. Cocok untuk dipakai sehari-hari dan mudah dipadukan dengan berbagai outfit.",
    color: "Beige",
    size: ["M", "L", "XL", "XXL"],
    image: ""
  },
  {
    id: 152,
    name: "Kemeja Poplin Puff Sleeve Blue Wanita",
    category: "kemeja",
    gender: "Wanita",
    price: 269000,
    stock: 21,
    description: "Kemeja poplin warna biru dengan detail puff sleeve dan kerah klasik. Memberikan tampilan feminin yang rapi untuk aktivitas maupun acara semi-formal.",
    color: "Blue",
    size: ["S", "M", "L", "XL"],
    image: ""
  },
  {
    id: 153,
    name: "Sepatu Loafers Suede Brown Pria",
    category: "sepatu",
    gender: "Pria",
    price: 499000,
    stock: 12,
    description: "Loafers berbahan suede warna brown dengan desain klasik dan tampilan elegan. Cocok dipadukan dengan chino, jeans, maupun celana bahan.",
    color: "Brown",
    size: ["39", "40", "41", "42", "43"],
    image: ""
  },
  {
    id: 154,
    name: "Piyama Katun Floral Blue Wanita",
    category: "piyama",
    gender: "Wanita",
    price: 199000,
    stock: 25,
    description: "Set piyama katun motif floral warna biru dengan bahan ringan dan nyaman. Cocok untuk tidur dan bersantai dengan tampilan feminin.",
    color: "Blue",
    size: ["S", "M", "L", "XL"],
    image: ""
  },
  {
    id: 155,
    name: "Hoodie Pullover Washed Grey Pria",
    category: "hoodie",
    gender: "Pria",
    price: 329000,
    stock: 19,
    description: "Hoodie pullover washed grey dengan tampilan sedikit pudar dan potongan relaxed fit. Cocok untuk gaya streetwear dan aktivitas santai.",
    color: "Washed Grey",
    size: ["M", "L", "XL", "XXL"],
    image: ""
  },
  {
    id: 156,
    name: "Sweater Cardigan Knit Brown Wanita",
    category: "sweater",
    gender: "Wanita",
    price: 339000,
    stock: 13,
    description: "Cardigan knit warna brown dengan kancing depan dan tekstur rajut lembut. Cocok digunakan sebagai outer untuk gaya kasual maupun semi-formal.",
    color: "Brown",
    size: ["S", "M", "L", "XL"],
    image: ""
  },
  {
    id: 157,
    name: "Tas Tote Nylon Navy Wanita",
    category: "tas",
    gender: "Wanita",
    price: 219000,
    stock: 30,
    description: "Tas tote berbahan nylon warna navy dengan desain ringan dan ruang luas. Cocok untuk kerja, kuliah, belanja, maupun aktivitas sehari-hari.",
    color: "Navy",
    size: ["All Size"],
    image: ""
  },
  {
    id: 158,
    name: "Kaos Graphic Minimalist Olive Wanita",
    category: "kaos",
    gender: "Wanita",
    price: 149000,
    stock: 29,
    description: "Kaos graphic minimalist warna olive dengan detail grafis sederhana dan bahan cotton nyaman. Cocok untuk gaya kasual modern.",
    color: "Olive",
    size: ["S", "M", "L", "XL"],
    image: ""
  },
  {
    id: 159,
    name: "Kebaya Brokat Payet Dusty Purple",
    category: "kebaya",
    gender: "Wanita",
    price: 875000,
    stock: 6,
    description: "Kebaya brokat warna dusty purple dengan detail payet yang memberikan kesan mewah. Cocok untuk pesta, lamaran, pernikahan, dan acara formal.",
    color: "Dusty Purple",
    size: ["S", "M", "L", "XL"],
    image: ""
  },
  {
    id: 160,
    name: "Kemeja Linen Camp Collar White Pria",
    category: "kemeja",
    gender: "Pria",
    price: 279000,
    stock: 22,
    description: "Kemeja linen camp collar warna putih dengan potongan santai dan bahan ringan. Cocok untuk liburan, acara santai, dan gaya musim panas.",
    color: "White",
    size: ["M", "L", "XL", "XXL"],
    image: ""
  },
  {
    id: 161,
    name: "Sepatu Slip On Knit Black Wanita",
    category: "sepatu",
    gender: "Wanita",
    price: 319000,
    stock: 27,
    description: "Sepatu slip on berbahan knit warna hitam dengan desain praktis dan ringan. Cocok digunakan untuk berjalan, bepergian, maupun aktivitas harian.",
    color: "Black",
    size: ["36", "37", "38", "39", "40"],
    image: ""
  },
  {
    id: 162,
    name: "Piyama Flannel Check Brown Pria",
    category: "piyama",
    gender: "Pria",
    price: 219000,
    stock: 18,
    description: "Set piyama flannel motif check warna brown dengan bahan lembut dan hangat. Cocok untuk tidur dan bersantai di rumah saat cuaca sejuk.",
    color: "Brown",
    size: ["M", "L", "XL", "XXL"],
    image: ""
  },
  {
    id: 163,
    name: "Hoodie Zip Minimalist Grey Wanita",
    category: "hoodie",
    gender: "Wanita",
    price: 299000,
    stock: 25,
    description: "Hoodie zip minimalist warna grey dengan resleting depan dan bahan fleece lembut. Cocok untuk gaya kasual, kuliah, dan perjalanan.",
    color: "Grey",
    size: ["S", "M", "L", "XL"],
    image: ""
  },
  {
    id: 164,
    name: "Sweater Quarter Zip Olive Pria",
    category: "sweater",
    gender: "Pria",
    price: 349000,
    stock: 17,
    description: "Sweater quarter zip warna olive dengan kerah tinggi dan desain modern. Cocok untuk tampilan smart casual maupun aktivitas santai.",
    color: "Olive",
    size: ["M", "L", "XL", "XXL"],
    image: ""
  },
  {
    id: 165,
    name: "Tas Shoulder Quilted Cream Wanita",
    category: "tas",
    gender: "Wanita",
    price: 329000,
    stock: 16,
    description: "Tas shoulder quilted warna cream dengan desain elegan dan tali bahu praktis. Cocok untuk acara santai, dinner, maupun aktivitas harian.",
    color: "Cream",
    size: ["All Size"],
    image: ""
  },
  {
    id: 166,
    name: "Kaos V-Neck Cotton Navy Pria",
    category: "kaos",
    gender: "Pria",
    price: 129000,
    stock: 39,
    description: "Kaos V-neck cotton warna navy dengan potongan regular dan bahan lembut. Cocok digunakan sebagai outfit utama untuk aktivitas sehari-hari.",
    color: "Navy",
    size: ["M", "L", "XL", "XXL"],
    image: ""
  },
  {
    id: 167,
    name: "Kebaya Encim Brokat Ivory",
    category: "kebaya",
    gender: "Wanita",
    price: 735000,
    stock: 10,
    description: "Kebaya encim berbahan brokat warna ivory dengan detail feminin dan tampilan elegan. Cocok untuk acara budaya, keluarga, dan perayaan formal.",
    color: "Ivory",
    size: ["S", "M", "L", "XL"],
    image: ""
  },
  {
    id: 168,
    name: "Kemeja Corduroy Overshirt Brown Pria",
    category: "kemeja",
    gender: "Pria",
    price: 339000,
    stock: 16,
    description: "Kemeja overshirt corduroy warna brown dengan tekstur khas dan potongan relaxed. Cocok digunakan sebagai outer untuk gaya kasual dan layering.",
    color: "Brown",
    size: ["M", "L", "XL", "XXL"],
    image: ""
  },
  {
    id: 169,
    name: "Sepatu Sneakers Platform White Wanita",
    category: "sepatu",
    gender: "Wanita",
    price: 419000,
    stock: 20,
    description: "Sneakers platform warna putih dengan sol sedikit tinggi dan desain clean. Cocok untuk gaya kasual, jalan-jalan, kuliah, dan aktivitas harian.",
    color: "White",
    size: ["36", "37", "38", "39", "40"],
    image: ""
  },
  {
    id: 170,
    name: "Piyama Satin Navy Pria",
    category: "piyama",
    gender: "Pria",
    price: 229000,
    stock: 16,
    description: "Set piyama satin warna navy dengan permukaan halus dan desain berkancing. Cocok digunakan untuk tidur maupun bersantai dengan nyaman.",
    color: "Navy",
    size: ["M", "L", "XL", "XXL"],
    image: ""
  },

  {
    id: 171,
    name: "Hoodie Fleece Basic Beige Pria",
    category: "hoodie",
    gender: "Pria",
    price: 299000,
    stock: 27,
    description: "Hoodie fleece basic warna beige dengan bahan lembut dan hangat. Desain polos membuatnya mudah dipadukan dengan jeans, jogger, maupun celana chino.",
    color: "Beige",
    size: ["M", "L", "XL", "XXL"],
    image: ""
  },
  {
    id: 172,
    name: "Sweater Turtleneck Knit Black Wanita",
    category: "sweater",
    gender: "Wanita",
    price: 359000,
    stock: 14,
    description: "Sweater turtleneck knit warna hitam dengan kerah tinggi dan tekstur rajut lembut. Cocok untuk tampilan elegan dan hangat saat cuaca sejuk.",
    color: "Black",
    size: ["S", "M", "L", "XL"],
    image: ""
  },
  {
    id: 173,
    name: "Tas Bucket Bag Black Wanita",
    category: "tas",
    gender: "Wanita",
    price: 349000,
    stock: 18,
    description: "Bucket bag warna hitam dengan bentuk fleksibel dan desain minimalis. Cocok digunakan untuk aktivitas harian dan membawa kebutuhan utama.",
    color: "Black",
    size: ["All Size"],
    image: ""
  },
  {
    id: 174,
    name: "Kaos Heavy Cotton White Pria",
    category: "kaos",
    gender: "Pria",
    price: 169000,
    stock: 36,
    description: "Kaos heavy cotton warna putih dengan bahan lebih tebal dan potongan regular. Cocok untuk gaya kasual dan dapat dipadukan dengan berbagai bawahan.",
    color: "White",
    size: ["M", "L", "XL", "XXL"],
    image: ""
  },
  {
    id: 175,
    name: "Kebaya Modern Lace Dusty Pink",
    category: "kebaya",
    gender: "Wanita",
    price: 785000,
    stock: 8,
    description: "Kebaya modern berbahan lace warna dusty pink dengan detail halus dan tampilan feminin. Cocok untuk wisuda, lamaran, pernikahan, dan acara formal.",
    color: "Dusty Pink",
    size: ["S", "M", "L", "XL"],
    image: ""
  },
  {
    id: 176,
    name: "Kemeja Flannel Check Brown Pria",
    category: "kemeja",
    gender: "Pria",
    price: 239000,
    stock: 28,
    description: "Kemeja flannel motif check warna brown dengan bahan lembut dan nyaman. Bisa digunakan sebagai kemeja maupun outer untuk gaya kasual.",
    color: "Brown",
    size: ["M", "L", "XL", "XXL"],
    image: ""
  },
  {
    id: 177,
    name: "Sepatu Derby Leather Brown Pria",
    category: "sepatu",
    gender: "Pria",
    price: 619000,
    stock: 9,
    description: "Sepatu derby berbahan kulit warna brown dengan desain formal klasik. Cocok digunakan untuk bekerja, acara resmi, dan tampilan smart casual.",
    color: "Brown",
    size: ["39", "40", "41", "42", "43"],
    image: ""
  },
  {
    id: 178,
    name: "Piyama Modal Soft Pink Wanita",
    category: "piyama",
    gender: "Wanita",
    price: 209000,
    stock: 22,
    description: "Set piyama modal warna soft pink dengan bahan lembut, ringan, dan nyaman di kulit. Cocok untuk tidur maupun bersantai di rumah.",
    color: "Soft Pink",
    size: ["S", "M", "L", "XL"],
    image: ""
  },
  {
    id: 179,
    name: "Hoodie Crop Fleece Black Wanita",
    category: "hoodie",
    gender: "Wanita",
    price: 289000,
    stock: 20,
    description: "Hoodie crop berbahan fleece warna hitam dengan potongan pendek dan desain modern. Cocok dipadukan dengan jeans atau celana high waist.",
    color: "Black",
    size: ["S", "M", "L", "XL"],
    image: ""
  },
  {
    id: 180,
    name: "Sweater Waffle Knit Grey Pria",
    category: "sweater",
    gender: "Pria",
    price: 289000,
    stock: 21,
    description: "Sweater waffle knit warna grey dengan tekstur kotak khas dan bahan lembut. Cocok untuk gaya kasual sehari-hari dan cuaca sejuk.",
    color: "Grey",
    size: ["M", "L", "XL", "XXL"],
    image: ""
  },
  {
    id: 181,
    name: "Tas Backpack Mini Sage Wanita",
    category: "tas",
    gender: "Wanita",
    price: 239000,
    stock: 24,
    description: "Tas backpack mini warna sage dengan ukuran compact dan bobot ringan. Cocok untuk jalan-jalan, kuliah, maupun aktivitas santai.",
    color: "Sage",
    size: ["All Size"],
    image: ""
  },
  {
    id: 182,
    name: "Kaos Striped Cotton Green Wanita",
    category: "kaos",
    gender: "Wanita",
    price: 149000,
    stock: 31,
    description: "Kaos cotton motif garis warna hijau dengan potongan nyaman. Cocok dipadukan dengan jeans, celana pendek, maupun rok.",
    color: "Green",
    size: ["S", "M", "L", "XL"],
    image: ""
  },
  {
    id: 183,
    name: "Kebaya Brokat Emerald Modern",
    category: "kebaya",
    gender: "Wanita",
    price: 845000,
    stock: 7,
    description: "Kebaya modern berbahan brokat warna emerald dengan detail elegan. Cocok untuk pesta, pernikahan, lamaran, dan acara formal.",
    color: "Emerald",
    size: ["S", "M", "L", "XL"],
    image: ""
  },
  {
    id: 184,
    name: "Kemeja Oxford Stripe Grey Pria",
    category: "kemeja",
    gender: "Pria",
    price: 299000,
    stock: 24,
    description: "Kemeja Oxford motif garis warna grey dengan kerah klasik dan potongan rapi. Cocok untuk bekerja, kuliah, maupun acara semi-formal.",
    color: "Grey",
    size: ["S", "M", "L", "XL"],
    image: ""
  },
  {
    id: 185,
    name: "Sepatu Mary Jane Flat Brown Wanita",
    category: "sepatu",
    gender: "Wanita",
    price: 299000,
    stock: 18,
    description: "Sepatu Mary Jane flat warna brown dengan strap sederhana dan desain feminin. Cocok untuk gaya kasual, kuliah, maupun acara semi-formal.",
    color: "Brown",
    size: ["36", "37", "38", "39", "40"],
    image: ""
  },
  {
    id: 186,
    name: "Piyama Katun Check Green Pria",
    category: "piyama",
    gender: "Pria",
    price: 189000,
    stock: 27,
    description: "Set piyama katun motif check warna hijau dengan bahan ringan dan nyaman. Cocok digunakan untuk tidur dan bersantai di rumah.",
    color: "Green",
    size: ["M", "L", "XL", "XXL"],
    image: ""
  },
  {
    id: 187,
    name: "Hoodie Oversize Washed Brown Pria",
    category: "hoodie",
    gender: "Pria",
    price: 329000,
    stock: 18,
    description: "Hoodie oversize washed brown dengan tampilan sedikit pudar dan bahan fleece lembut. Cocok untuk gaya streetwear dan outfit santai.",
    color: "Washed Brown",
    size: ["M", "L", "XL", "XXL"],
    image: ""
  },
  {
    id: 188,
    name: "Sweater Knit Polo Collar Cream Wanita",
    category: "sweater",
    gender: "Wanita",
    price: 329000,
    stock: 15,
    description: "Sweater knit dengan kerah polo warna cream dan tekstur rajut lembut. Cocok untuk tampilan smart casual maupun gaya sehari-hari.",
    color: "Cream",
    size: ["S", "M", "L", "XL"],
    image: ""
  },
  {
    id: 189,
    name: "Tas Hobo Soft Black Wanita",
    category: "tas",
    gender: "Wanita",
    price: 359000,
    stock: 13,
    description: "Tas hobo soft warna hitam dengan bentuk fleksibel dan desain minimalis. Cocok untuk membawa kebutuhan harian dengan tampilan elegan.",
    color: "Black",
    size: ["All Size"],
    image: ""
  },
  {
    id: 190,
    name: "Kaos Boxy Graphic Navy Pria",
    category: "kaos",
    gender: "Pria",
    price: 159000,
    stock: 33,
    description: "Kaos boxy graphic warna navy dengan potongan sedikit longgar dan detail grafis modern. Cocok untuk gaya streetwear dan kasual.",
    color: "Navy",
    size: ["M", "L", "XL", "XXL"],
    image: ""
  },

  {
    id: 191,
    name: "Kemeja Satin Relaxed Black Wanita",
    category: "kemeja",
    gender: "Wanita",
    price: 289000,
    stock: 17,
    description: "Kemeja satin relaxed warna hitam dengan bahan halus dan tampilan elegan. Cocok untuk dinner, acara semi-formal, maupun gaya kasual modern.",
    color: "Black",
    size: ["S", "M", "L", "XL"],
    image: ""
  },
  {
    id: 192,
    name: "Sepatu Sneakers Canvas Beige Wanita",
    category: "sepatu",
    gender: "Wanita",
    price: 289000,
    stock: 29,
    description: "Sneakers canvas warna beige dengan desain sederhana dan sol fleksibel. Cocok untuk kuliah, jalan-jalan, dan aktivitas sehari-hari.",
    color: "Beige",
    size: ["36", "37", "38", "39", "40"],
    image: ""
  },
  {
    id: 193,
    name: "Piyama Rayon Floral Lavender Wanita",
    category: "piyama",
    gender: "Wanita",
    price: 219000,
    stock: 18,
    description: "Set piyama rayon motif floral warna lavender dengan bahan lembut dan ringan. Cocok untuk tidur dan bersantai dengan tampilan feminin.",
    color: "Lavender",
    size: ["S", "M", "L", "XL"],
    image: ""
  },
  {
    id: 194,
    name: "Hoodie Graphic Charcoal Pria",
    category: "hoodie",
    gender: "Pria",
    price: 319000,
    stock: 22,
    description: "Hoodie graphic warna charcoal dengan detail grafis pada bagian depan dan bahan fleece lembut. Cocok untuk streetwear dan aktivitas santai.",
    color: "Charcoal",
    size: ["M", "L", "XL", "XXL"],
    image: ""
  },
  {
    id: 195,
    name: "Sweater Crewneck Soft Blue Wanita",
    category: "sweater",
    gender: "Wanita",
    price: 279000,
    stock: 23,
    description: "Sweater crewneck warna soft blue dengan bahan lembut dan potongan regular. Cocok untuk gaya kasual dan digunakan saat cuaca sejuk.",
    color: "Soft Blue",
    size: ["S", "M", "L", "XL"],
    image: ""
  },
  {
    id: 196,
    name: "Tas Messenger Nylon Grey Pria",
    category: "tas",
    gender: "Pria",
    price: 219000,
    stock: 27,
    description: "Tas messenger nylon warna grey dengan desain ringan dan beberapa kompartemen. Cocok untuk membawa barang penting saat kerja, kuliah, atau bepergian.",
    color: "Grey",
    size: ["All Size"],
    image: ""
  },
  {
    id: 197,
    name: "Kaos Ribbed Slim Fit Brown Wanita",
    category: "kaos",
    gender: "Wanita",
    price: 139000,
    stock: 26,
    description: "Kaos ribbed slim fit warna brown dengan tekstur bergaris dan bahan elastis. Cocok dipadukan dengan jeans, rok, maupun celana high waist.",
    color: "Brown",
    size: ["S", "M", "L", "XL"],
    image: ""
  },
  {
    id: 198,
    name: "Kebaya Kutubaru Brokat Maroon",
    category: "kebaya",
    gender: "Wanita",
    price: 775000,
    stock: 9,
    description: "Kebaya kutubaru berbahan brokat warna maroon dengan tampilan klasik dan elegan. Cocok untuk acara adat, keluarga, pernikahan, dan acara resmi.",
    color: "Maroon",
    size: ["S", "M", "L", "XL"],
    image: ""
  },
  {
    id: 199,
    name: "Kemeja Linen Oversize Sand Wanita",
    category: "kemeja",
    gender: "Wanita",
    price: 279000,
    stock: 20,
    description: "Kemeja linen oversize warna sand dengan bahan ringan dan potongan longgar. Cocok untuk gaya kasual, liburan, dan aktivitas sehari-hari.",
    color: "Sand",
    size: ["S", "M", "L", "XL"],
    image: ""
  },
  {
    id: 200,
    name: "Sepatu Running Lightweight Grey Pria",
    category: "sepatu",
    gender: "Pria",
    price: 409000,
    stock: 22,
    description: "Sepatu running lightweight warna grey dengan desain breathable dan konstruksi ringan. Cocok untuk jogging, olahraga ringan, dan aktivitas harian.",
    color: "Grey",
    size: ["39", "40", "41", "42", "43"],
    image: ""
  },

  {
    id: 201,
    name: "Piyama Satin Burgundy Wanita",
    category: "piyama",
    gender: "Wanita",
    price: 259000,
    stock: 13,
    description: "Set piyama satin warna burgundy dengan permukaan halus dan tampilan mewah. Cocok untuk tidur maupun bersantai dengan nyaman.",
    color: "Burgundy",
    size: ["S", "M", "L", "XL"],
    image: ""
  },
  {
    id: 202,
    name: "Hoodie Basic Navy Wanita",
    category: "hoodie",
    gender: "Wanita",
    price: 289000,
    stock: 28,
    description: "Hoodie basic warna navy dengan bahan fleece lembut dan desain polos. Cocok untuk gaya kasual, kuliah, perjalanan, maupun aktivitas santai.",
    color: "Navy",
    size: ["S", "M", "L", "XL"],
    image: ""
  },
  {
    id: 203,
    name: "Sweater Mock Neck Brown Pria",
    category: "sweater",
    gender: "Pria",
    price: 319000,
    stock: 18,
    description: "Sweater mock neck warna brown dengan kerah tinggi dan tekstur rajut lembut. Cocok untuk gaya kasual yang lebih rapi saat cuaca sejuk.",
    color: "Brown",
    size: ["M", "L", "XL", "XXL"],
    image: ""
  },
  {
    id: 204,
    name: "Tas Tote Canvas Sage Wanita",
    category: "tas",
    gender: "Wanita",
    price: 189000,
    stock: 34,
    description: "Tas tote canvas warna sage dengan ruang luas dan desain sederhana. Cocok untuk kuliah, kerja, belanja, dan aktivitas sehari-hari.",
    color: "Sage",
    size: ["All Size"],
    image: ""
  },
  {
    id: 205,
    name: "Kaos Polo Pique White Pria",
    category: "kaos",
    gender: "Pria",
    price: 179000,
    stock: 38,
    description: "Kaos polo berbahan pique warna putih dengan kerah klasik dan kancing depan. Cocok untuk tampilan kasual yang lebih rapi.",
    color: "White",
    size: ["M", "L", "XL", "XXL"],
    image: ""
  },
  {
    id: 206,
    name: "Kebaya Modern Peplum Ivory",
    category: "kebaya",
    gender: "Wanita",
    price: 745000,
    stock: 11,
    description: "Kebaya modern peplum warna ivory dengan detail feminin dan potongan elegan. Cocok untuk acara keluarga, lamaran, wisuda, dan perayaan formal.",
    color: "Ivory",
    size: ["S", "M", "L", "XL"],
    image: ""
  },
  {
    id: 207,
    name: "Kemeja Denim Light Blue Pria",
    category: "kemeja",
    gender: "Pria",
    price: 299000,
    stock: 19,
    description: "Kemeja denim light blue dengan bahan denim ringan dan potongan regular. Cocok digunakan sebagai kemeja maupun outer untuk gaya kasual.",
    color: "Light Blue",
    size: ["M", "L", "XL", "XXL"],
    image: ""
  },
  {
    id: 208,
    name: "Sepatu Slip On Canvas Black Pria",
    category: "sepatu",
    gender: "Pria",
    price: 279000,
    stock: 30,
    description: "Sepatu slip on canvas warna hitam dengan desain praktis tanpa tali. Cocok untuk aktivitas santai, kuliah, jalan-jalan, dan perjalanan.",
    color: "Black",
    size: ["39", "40", "41", "42", "43"],
    image: ""
  },
  {
    id: 209,
    name: "Piyama Katun Basic Dusty Blue Wanita",
    category: "piyama",
    gender: "Wanita",
    price: 179000,
    stock: 32,
    description: "Set piyama katun basic warna dusty blue dengan bahan lembut dan ringan. Desain sederhana memberikan kenyamanan untuk tidur dan bersantai.",
    color: "Dusty Blue",
    size: ["S", "M", "L", "XL"],
    image: ""
  },
  {
    id: 210,
    name: "Hoodie Half Zip Black Pria",
    category: "hoodie",
    gender: "Pria",
    price: 329000,
    stock: 16,
    description: "Hoodie half zip warna hitam dengan resleting pendek pada bagian depan dan bahan fleece nyaman. Cocok untuk gaya sporty dan kasual.",
    color: "Black",
    size: ["M", "L", "XL", "XXL"],
    image: ""
  },
  {
    id: 211,
    name: "Sweater Cardigan Soft Pink Wanita",
    category: "sweater",
    gender: "Wanita",
    price: 319000,
    stock: 20,
    description: "Cardigan sweater warna soft pink dengan kancing depan dan bahan rajut lembut. Cocok sebagai outer untuk gaya feminin dan kasual.",
    color: "Soft Pink",
    size: ["S", "M", "L", "XL"],
    image: ""
  },
  {
    id: 212,
    name: "Tas Crossbody Canvas Black Pria",
    category: "tas",
    gender: "Pria",
    price: 199000,
    stock: 32,
    description: "Tas crossbody canvas warna hitam dengan ukuran compact dan tali bahu adjustable. Cocok untuk membawa barang kecil saat bepergian.",
    color: "Black",
    size: ["All Size"],
    image: ""
  },
  {
    id: 213,
    name: "Kaos Oversize Washed Green Wanita",
    category: "kaos",
    gender: "Wanita",
    price: 159000,
    stock: 30,
    description: "Kaos oversize washed green dengan tampilan sedikit pudar dan potongan longgar. Cocok untuk gaya kasual modern dan streetwear.",
    color: "Washed Green",
    size: ["S", "M", "L", "XL"],
    image: ""
  },
  {
    id: 214,
    name: "Kebaya Brokat Champagne Modern",
    category: "kebaya",
    gender: "Wanita",
    price: 895000,
    stock: 6,
    description: "Kebaya brokat warna champagne dengan detail elegan dan tampilan mewah. Cocok untuk pesta, pernikahan, lamaran, dan acara formal.",
    color: "Champagne",
    size: ["S", "M", "L", "XL"],
    image: ""
  },
  {
    id: 215,
    name: "Kemeja Oxford Slim Fit Grey Pria",
    category: "kemeja",
    gender: "Pria",
    price: 319000,
    stock: 23,
    description: "Kemeja Oxford slim fit warna grey dengan kerah klasik dan kancing depan. Cocok untuk bekerja, kuliah, maupun gaya smart casual.",
    color: "Grey",
    size: ["S", "M", "L", "XL"],
    image: ""
  },
  {
    id: 216,
    name: "Sepatu Sneakers Retro Beige Wanita",
    category: "sepatu",
    gender: "Wanita",
    price: 419000,
    stock: 18,
    description: "Sneakers retro warna beige dengan desain klasik dan sol nyaman. Cocok digunakan untuk jalan-jalan, kuliah, dan aktivitas sehari-hari.",
    color: "Beige",
    size: ["36", "37", "38", "39", "40"],
    image: ""
  },
  {
    id: 217,
    name: "Piyama Rayon Motif Daun Green Pria",
    category: "piyama",
    gender: "Pria",
    price: 209000,
    stock: 17,
    description: "Set piyama rayon motif daun warna green dengan bahan ringan dan lembut. Cocok digunakan untuk tidur dan bersantai di rumah.",
    color: "Green",
    size: ["M", "L", "XL", "XXL"],
    image: ""
  },
  {
    id: 218,
    name: "Hoodie Oversize Charcoal Wanita",
    category: "hoodie",
    gender: "Wanita",
    price: 309000,
    stock: 23,
    description: "Hoodie oversize warna charcoal dengan bahan fleece lembut dan potongan longgar. Cocok untuk gaya kasual, streetwear, dan aktivitas santai.",
    color: "Charcoal",
    size: ["S", "M", "L", "XL"],
    image: ""
  },
  {
    id: 219,
    name: "Sweater Crewneck Olive Pria",
    category: "sweater",
    gender: "Pria",
    price: 289000,
    stock: 25,
    description: "Sweater crewneck warna olive dengan bahan lembut dan desain minimalis. Cocok dipadukan dengan jeans, chino, atau celana kasual.",
    color: "Olive",
    size: ["M", "L", "XL", "XXL"],
    image: ""
  },
  {
    id: 220,
    name: "Tas Shoulder Chain Burgundy Wanita",
    category: "tas",
    gender: "Wanita",
    price: 329000,
    stock: 15,
    description: "Tas shoulder warna burgundy dengan detail rantai pada tali dan desain elegan. Cocok untuk acara semi-formal, dinner, maupun penggunaan harian.",
    color: "Burgundy",
    size: ["All Size"],
    image: ""
  },

  {
    id: 221,
    name: "Kaos Henley Cotton Cream Pria",
    category: "kaos",
    gender: "Pria",
    price: 159000,
    stock: 28,
    description: "Kaos henley cotton warna cream dengan detail kancing pada bagian leher. Cocok untuk tampilan kasual yang sederhana namun tetap rapi.",
    color: "Cream",
    size: ["M", "L", "XL", "XXL"],
    image: ""
  },
  {
    id: 222,
    name: "Kebaya Lace Modern Black",
    category: "kebaya",
    gender: "Wanita",
    price: 815000,
    stock: 8,
    description: "Kebaya modern berbahan lace warna hitam dengan desain elegan dan feminin. Cocok untuk pesta, pernikahan, acara malam, dan perayaan formal.",
    color: "Black",
    size: ["S", "M", "L", "XL"],
    image: ""
  },
  {
    id: 223,
    name: "Kemeja Flannel Kotak Green Pria",
    category: "kemeja",
    gender: "Pria",
    price: 229000,
    stock: 30,
    description: "Kemeja flannel motif kotak warna green dengan bahan lembut dan nyaman. Cocok digunakan sebagai kemeja maupun outer untuk gaya kasual.",
    color: "Green",
    size: ["M", "L", "XL", "XXL"],
    image: ""
  },
  {
    id: 224,
    name: "Sepatu Ballet Flat Nude Wanita",
    category: "sepatu",
    gender: "Wanita",
    price: 259000,
    stock: 22,
    description: "Sepatu ballet flat warna nude dengan desain feminin dan sederhana. Cocok dipadukan dengan dress, rok, maupun celana untuk aktivitas harian.",
    color: "Nude",
    size: ["36", "37", "38", "39", "40"],
    image: ""
  },
  {
    id: 225,
    name: "Piyama Satin Black Pria",
    category: "piyama",
    gender: "Pria",
    price: 239000,
    stock: 15,
    description: "Set piyama satin warna hitam dengan bahan halus dan desain berkancing. Cocok digunakan untuk tidur dan bersantai dengan tampilan rapi.",
    color: "Black",
    size: ["M", "L", "XL", "XXL"],
    image: ""
  },
  {
    id: 226,
    name: "Hoodie Zip Basic Beige Wanita",
    category: "hoodie",
    gender: "Wanita",
    price: 299000,
    stock: 27,
    description: "Hoodie zip basic warna beige dengan bahan fleece lembut dan resleting depan. Cocok untuk kuliah, perjalanan, dan gaya kasual sehari-hari.",
    color: "Beige",
    size: ["S", "M", "L", "XL"],
    image: ""
  },
  {
    id: 227,
    name: "Sweater Knit Cable Cream Pria",
    category: "sweater",
    gender: "Pria",
    price: 329000,
    stock: 19,
    description: "Sweater cable knit warna cream dengan tekstur rajutan klasik dan bahan hangat. Cocok digunakan untuk gaya kasual saat cuaca sejuk.",
    color: "Cream",
    size: ["M", "L", "XL", "XXL"],
    image: ""
  },
  {
    id: 228,
    name: "Tas Tote Leather Brown Wanita",
    category: "tas",
    gender: "Wanita",
    price: 459000,
    stock: 12,
    description: "Tas tote berbahan kulit warna brown dengan desain structured dan ruang luas. Cocok untuk bekerja, kuliah, dan membawa perlengkapan harian.",
    color: "Brown",
    size: ["All Size"],
    image: ""
  },
  {
    id: 229,
    name: "Kaos Graphic Retro Brown Wanita",
    category: "kaos",
    gender: "Wanita",
    price: 159000,
    stock: 31,
    description: "Kaos graphic retro warna brown dengan detail ilustrasi bernuansa vintage. Berbahan cotton lembut dan cocok untuk gaya kasual.",
    color: "Brown",
    size: ["S", "M", "L", "XL"],
    image: ""
  },
  {
    id: 230,
    name: "Kebaya Brokat Floral Soft Lilac",
    category: "kebaya",
    gender: "Wanita",
    price: 735000,
    stock: 10,
    description: "Kebaya brokat motif floral warna soft lilac dengan detail feminin dan tampilan anggun. Cocok untuk wisuda, lamaran, acara keluarga, dan pesta.",
    color: "Soft Lilac",
    size: ["S", "M", "L", "XL"],
    image: ""
  },
  {
    id: 231,
    name: "Kemeja Linen Cuban Collar Olive Wanita",
    category: "kemeja",
    gender: "Wanita",
    price: 279000,
    stock: 21,
    description: "Kemeja linen Cuban collar warna olive dengan bahan ringan dan potongan santai. Cocok untuk liburan dan gaya kasual sehari-hari.",
    color: "Olive",
    size: ["S", "M", "L", "XL"],
    image: ""
  },
  {
    id: 232,
    name: "Sepatu Sneakers White Navy Pria",
    category: "sepatu",
    gender: "Pria",
    price: 399000,
    stock: 24,
    description: "Sneakers kombinasi warna putih dan navy dengan desain minimalis. Cocok untuk aktivitas sehari-hari, kuliah, jalan-jalan, dan gaya kasual.",
    color: "White Navy",
    size: ["39", "40", "41", "42", "43"],
    image: ""
  },
  {
    id: 233,
    name: "Piyama Katun Stripe Grey Wanita",
    category: "piyama",
    gender: "Wanita",
    price: 189000,
    stock: 29,
    description: "Set piyama katun motif stripe warna grey dengan bahan ringan dan lembut. Nyaman untuk tidur maupun bersantai di rumah.",
    color: "Grey",
    size: ["S", "M", "L", "XL"],
    image: ""
  },
  {
    id: 234,
    name: "Hoodie Pullover Fleece Navy Pria",
    category: "hoodie",
    gender: "Pria",
    price: 309000,
    stock: 25,
    description: "Hoodie pullover fleece warna navy dengan bahan lembut dan hangat. Cocok untuk gaya kasual, streetwear, dan aktivitas luar ruangan.",
    color: "Navy",
    size: ["M", "L", "XL", "XXL"],
    image: ""
  },
  {
    id: 235,
    name: "Sweater V-Neck Knit Dusty Pink Wanita",
    category: "sweater",
    gender: "Wanita",
    price: 299000,
    stock: 18,
    description: "Sweater V-neck knit warna dusty pink dengan bahan rajut lembut dan potongan feminin. Cocok dipadukan dengan jeans maupun rok.",
    color: "Dusty Pink",
    size: ["S", "M", "L", "XL"],
    image: ""
  },
  {
    id: 236,
    name: "Tas Crossbody Nylon Navy Pria",
    category: "tas",
    gender: "Pria",
    price: 189000,
    stock: 33,
    description: "Tas crossbody nylon warna navy dengan ukuran compact dan tali adjustable. Cocok membawa ponsel, dompet, kunci, dan barang kecil.",
    color: "Navy",
    size: ["All Size"],
    image: ""
  },
  {
    id: 237,
    name: "Kaos Oversize Pocket Grey Pria",
    category: "kaos",
    gender: "Pria",
    price: 139000,
    stock: 40,
    description: "Kaos oversize warna grey dengan detail pocket pada bagian dada dan bahan cotton lembut. Cocok untuk gaya kasual dan streetwear.",
    color: "Grey",
    size: ["M", "L", "XL", "XXL"],
    image: ""
  },
  {
    id: 238,
    name: "Kebaya Modern Velvet Navy",
    category: "kebaya",
    gender: "Wanita",
    price: 845000,
    stock: 7,
    description: "Kebaya modern berbahan velvet warna navy dengan tampilan mewah dan elegan. Cocok untuk pesta malam, pernikahan, dan acara formal.",
    color: "Navy",
    size: ["S", "M", "L", "XL"],
    image: ""
  },
  {
    id: 239,
    name: "Kemeja Satin Oversize Burgundy Wanita",
    category: "kemeja",
    gender: "Wanita",
    price: 299000,
    stock: 16,
    description: "Kemeja satin oversize warna burgundy dengan bahan halus dan potongan longgar. Cocok untuk gaya kasual modern maupun acara semi-formal.",
    color: "Burgundy",
    size: ["S", "M", "L", "XL"],
    image: ""
  },
  {
    id: 240,
    name: "Sepatu Canvas High Top White Pria",
    category: "sepatu",
    gender: "Pria",
    price: 329000,
    stock: 21,
    description: "Sepatu canvas high top warna putih dengan desain klasik dan bagian atas menutupi pergelangan kaki. Cocok untuk gaya kasual dan streetwear.",
    color: "White",
    size: ["39", "40", "41", "42", "43"],
    image: ""
  }
];

